// https://syzkaller.appspot.com/bug?id=004b0f7b61d4901cbfecfc33de7996e8cbe0a278
// autogenerated by syzkaller (http://github.com/google/syzkaller)

#define _GNU_SOURCE
#include <endian.h>
#include <stdint.h>
#include <string.h>
#include <sys/syscall.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};
void loop()
{
  long res = 0;
  res = syscall(__NR_socket, 0x2b, 1, 0);
  if (res != -1)
    r[0] = res;
  *(uint64_t*)0x20000100 = 0;
  *(uint32_t*)0x20000108 = 0;
  *(uint64_t*)0x20000110 = 0x200000c0;
  *(uint64_t*)0x200000c0 = 0x20000000;
  *(uint64_t*)0x200000c8 = 0;
  *(uint64_t*)0x200000d0 = 0x20000180;
  *(uint64_t*)0x200000d8 = 0;
  *(uint64_t*)0x20000118 = 2;
  *(uint64_t*)0x20000120 = 0x20000780;
  *(uint64_t*)0x20000128 = 0;
  *(uint32_t*)0x20000130 = 0x10;
  syscall(__NR_sendmsg, r[0], 0x20000100, 0x24000815);
}

int main()
{
  syscall(__NR_mmap, 0x20000000, 0x1000000, 3, 0x32, -1, 0);
  loop();
  return 0;
}
