// https://syzkaller.appspot.com/bug?id=09b56d900d511e06f0f5331c2afb941aa083e198
// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <endian.h>
#include <errno.h>
#include <fcntl.h>
#include <sched.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mount.h>
#include <sys/prctl.h>
#include <sys/resource.h>
#include <sys/stat.h>
#include <sys/swap.h>
#include <sys/syscall.h>
#include <sys/time.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <unistd.h>

#include <linux/capability.h>
#include <linux/falloc.h>

#ifndef __NR_userfaultfd
#define __NR_userfaultfd 323
#endif

static void use_temporary_dir(void)
{
  char tmpdir_template[] = "./syzkaller.XXXXXX";
  char* tmpdir = mkdtemp(tmpdir_template);
  if (!tmpdir)
    exit(1);
  if (chmod(tmpdir, 0777))
    exit(1);
  if (chdir(tmpdir))
    exit(1);
}

static bool write_file(const char* file, const char* what, ...)
{
  char buf[1024];
  va_list args;
  va_start(args, what);
  vsnprintf(buf, sizeof(buf), what, args);
  va_end(args);
  buf[sizeof(buf) - 1] = 0;
  int len = strlen(buf);
  int fd = open(file, O_WRONLY | O_CLOEXEC);
  if (fd == -1)
    return false;
  if (write(fd, buf, len) != len) {
    int err = errno;
    close(fd);
    errno = err;
    return false;
  }
  close(fd);
  return true;
}

static int runcmdline(char* cmdline)
{
  int ret = system(cmdline);
  if (ret) {
  }
  return ret;
}

static void setup_gadgetfs();
static void setup_binderfs();
static void setup_fusectl();
static void sandbox_common_mount_tmpfs(void)
{
  write_file("/proc/sys/fs/mount-max", "100000");
  if (mkdir("./syz-tmp", 0777))
    exit(1);
  if (mount("", "./syz-tmp", "tmpfs", 0, NULL))
    exit(1);
  if (mkdir("./syz-tmp/newroot", 0777))
    exit(1);
  if (mkdir("./syz-tmp/newroot/dev", 0700))
    exit(1);
  unsigned bind_mount_flags = MS_BIND | MS_REC | MS_PRIVATE;
  if (mount("/dev", "./syz-tmp/newroot/dev", NULL, bind_mount_flags, NULL))
    exit(1);
  if (mkdir("./syz-tmp/newroot/proc", 0700))
    exit(1);
  if (mount("syz-proc", "./syz-tmp/newroot/proc", "proc", 0, NULL))
    exit(1);
  if (mkdir("./syz-tmp/newroot/selinux", 0700))
    exit(1);
  const char* selinux_path = "./syz-tmp/newroot/selinux";
  if (mount("/selinux", selinux_path, NULL, bind_mount_flags, NULL)) {
    if (errno != ENOENT)
      exit(1);
    if (mount("/sys/fs/selinux", selinux_path, NULL, bind_mount_flags, NULL) &&
        errno != ENOENT)
      exit(1);
  }
  if (mkdir("./syz-tmp/newroot/sys", 0700))
    exit(1);
  if (mount("/sys", "./syz-tmp/newroot/sys", 0, bind_mount_flags, NULL))
    exit(1);
  if (mount("/sys/kernel/debug", "./syz-tmp/newroot/sys/kernel/debug", NULL,
            bind_mount_flags, NULL) &&
      errno != ENOENT)
    exit(1);
  if (mount("/sys/fs/smackfs", "./syz-tmp/newroot/sys/fs/smackfs", NULL,
            bind_mount_flags, NULL) &&
      errno != ENOENT)
    exit(1);
  if (mount("/proc/sys/fs/binfmt_misc",
            "./syz-tmp/newroot/proc/sys/fs/binfmt_misc", NULL, bind_mount_flags,
            NULL) &&
      errno != ENOENT)
    exit(1);
  if (mkdir("./syz-tmp/newroot/syz-inputs", 0700))
    exit(1);
  if (mount("/syz-inputs", "./syz-tmp/newroot/syz-inputs", NULL,
            bind_mount_flags | MS_RDONLY, NULL) &&
      errno != ENOENT)
    exit(1);
  if (mkdir("./syz-tmp/pivot", 0777))
    exit(1);
  if (syscall(SYS_pivot_root, "./syz-tmp", "./syz-tmp/pivot")) {
    if (chdir("./syz-tmp"))
      exit(1);
  } else {
    if (chdir("/"))
      exit(1);
    if (umount2("./pivot", MNT_DETACH))
      exit(1);
  }
  if (chroot("./newroot"))
    exit(1);
  if (chdir("/"))
    exit(1);
  setup_gadgetfs();
  setup_binderfs();
  setup_fusectl();
}

static void setup_gadgetfs()
{
  if (mkdir("/dev/gadgetfs", 0777)) {
  }
  if (mount("gadgetfs", "/dev/gadgetfs", "gadgetfs", 0, NULL)) {
  }
}

static void setup_fusectl()
{
  if (mount(0, "/sys/fs/fuse/connections", "fusectl", 0, 0)) {
  }
}

static void setup_binderfs()
{
  if (mkdir("/dev/binderfs", 0777)) {
  }
  if (mount("binder", "/dev/binderfs", "binder", 0, NULL)) {
  }
}

static void loop();

static void sandbox_common()
{
  prctl(PR_SET_PDEATHSIG, SIGKILL, 0, 0, 0);
  if (getppid() == 1)
    exit(1);
  struct rlimit rlim;
  rlim.rlim_cur = rlim.rlim_max = (200 << 20);
  setrlimit(RLIMIT_AS, &rlim);
  rlim.rlim_cur = rlim.rlim_max = 32 << 20;
  setrlimit(RLIMIT_MEMLOCK, &rlim);
  rlim.rlim_cur = rlim.rlim_max = 136 << 20;
  setrlimit(RLIMIT_FSIZE, &rlim);
  rlim.rlim_cur = rlim.rlim_max = 1 << 20;
  setrlimit(RLIMIT_STACK, &rlim);
  rlim.rlim_cur = rlim.rlim_max = 128 << 20;
  setrlimit(RLIMIT_CORE, &rlim);
  rlim.rlim_cur = rlim.rlim_max = 256;
  setrlimit(RLIMIT_NOFILE, &rlim);
  if (unshare(CLONE_NEWNS)) {
  }
  if (mount(NULL, "/", NULL, MS_REC | MS_PRIVATE, NULL)) {
  }
  if (unshare(CLONE_NEWIPC)) {
  }
  if (unshare(0x02000000)) {
  }
  if (unshare(CLONE_NEWUTS)) {
  }
  if (unshare(CLONE_SYSVSEM)) {
  }
  typedef struct {
    const char* name;
    const char* value;
  } sysctl_t;
  static const sysctl_t sysctls[] = {
      {"/proc/sys/kernel/shmmax", "16777216"},
      {"/proc/sys/kernel/shmall", "536870912"},
      {"/proc/sys/kernel/shmmni", "1024"},
      {"/proc/sys/kernel/msgmax", "8192"},
      {"/proc/sys/kernel/msgmni", "1024"},
      {"/proc/sys/kernel/msgmnb", "1024"},
      {"/proc/sys/kernel/sem", "1024 1048576 500 1024"},
  };
  unsigned i;
  for (i = 0; i < sizeof(sysctls) / sizeof(sysctls[0]); i++)
    write_file(sysctls[i].name, sysctls[i].value);
}

static int wait_for_loop(int pid)
{
  if (pid < 0)
    exit(1);
  int status = 0;
  while (waitpid(-1, &status, __WALL) != pid) {
  }
  return WEXITSTATUS(status);
}

static void drop_caps(void)
{
  struct __user_cap_header_struct cap_hdr = {};
  struct __user_cap_data_struct cap_data[2] = {};
  cap_hdr.version = _LINUX_CAPABILITY_VERSION_3;
  cap_hdr.pid = getpid();
  if (syscall(SYS_capget, &cap_hdr, &cap_data))
    exit(1);
  const int drop = (1 << CAP_SYS_PTRACE) | (1 << CAP_SYS_NICE);
  cap_data[0].effective &= ~drop;
  cap_data[0].permitted &= ~drop;
  cap_data[0].inheritable &= ~drop;
  if (syscall(SYS_capset, &cap_hdr, &cap_data))
    exit(1);
}

static int do_sandbox_none(void)
{
  if (unshare(CLONE_NEWPID)) {
  }
  int pid = fork();
  if (pid != 0)
    return wait_for_loop(pid);
  sandbox_common();
  drop_caps();
  if (unshare(CLONE_NEWNET)) {
  }
  write_file("/proc/sys/net/ipv4/ping_group_range", "0 65535");
  sandbox_common_mount_tmpfs();
  loop();
  exit(1);
}

#define SWAP_FILE "./swap-file"
#define SWAP_FILE_SIZE (128 * 1000 * 1000)

static const char* setup_swap()
{
  swapoff(SWAP_FILE);
  unlink(SWAP_FILE);
  int fd = open(SWAP_FILE, O_CREAT | O_WRONLY | O_CLOEXEC, 0600);
  if (fd == -1)
    return "swap file open failed";
  fallocate(fd, FALLOC_FL_ZERO_RANGE, 0, SWAP_FILE_SIZE);
  close(fd);
  char cmdline[64];
  sprintf(cmdline, "mkswap %s", SWAP_FILE);
  if (runcmdline(cmdline))
    return "mkswap failed";
  if (swapon(SWAP_FILE, SWAP_FLAG_PREFER) == 1)
    return "swapon failed";
  return NULL;
}

uint64_t r[1] = {0xffffffffffffffff};

void loop(void)
{
  intptr_t res = 0;
  if (write(1, "executing program\n", sizeof("executing program\n") - 1)) {
  }
  //  mlock arguments: [
  //    addr: VMA[0x2000]
  //    size: len = 0x2000 (8 bytes)
  //  ]
  syscall(__NR_mlock, /*addr=*/0x200000ffe000ul, /*size=*/0x2000ul);
  //  munlock arguments: [
  //    addr: VMA[0x4000]
  //    size: len = 0x4000 (8 bytes)
  //  ]
  syscall(__NR_munlock, /*addr=*/0x200000ffc000ul, /*size=*/0x4000ul);
  //  madvise arguments: [
  //    addr: VMA[0x4000]
  //    len: len = 0x4000 (8 bytes)
  //    advice: madvise_flags = 0x15 (8 bytes)
  //  ]
  syscall(__NR_madvise, /*addr=*/0x200000ffc000ul, /*len=*/0x4000ul,
          /*advice=MADV_PAGEOUT*/ 0x15ul);
  //  userfaultfd arguments: [
  //    flags: userfaultfd_flags = 0x801 (8 bytes)
  //  ]
  //  returns fd_uffd
  res = syscall(__NR_userfaultfd,
                /*flags=UFFD_USER_MODE_ONLY|O_NONBLOCK*/ 0x801ul);
  if (res != -1)
    r[0] = res;
  //  ioctl$UFFDIO_API arguments: [
  //    fd: fd_uffd (resource)
  //    cmd: const = 0xc018aa3f (4 bytes)
  //    arg: ptr[in, uffdio_api] {
  //      uffdio_api {
  //        api: const = 0xaa (8 bytes)
  //        featur: uffdio_features = 0x10 (8 bytes)
  //        ioctls: const = 0x0 (8 bytes)
  //      }
  //    }
  //  ]
  *(uint64_t*)0x200000000040 = 0xaa;
  *(uint64_t*)0x200000000048 = 0x10;
  *(uint64_t*)0x200000000050 = 0;
  syscall(__NR_ioctl, /*fd=*/r[0], /*cmd=*/0xc018aa3f,
          /*arg=*/0x200000000040ul);
  //  ioctl$UFFDIO_REGISTER arguments: [
  //    fd: fd_uffd (resource)
  //    cmd: const = 0xc020aa00 (4 bytes)
  //    arg: ptr[in, uffdio_register] {
  //      uffdio_register {
  //        range: uffdio_range {
  //          start: VMA[0x3000]
  //          len: len = 0x3000 (8 bytes)
  //        }
  //        mode: uffdio_register_mode = 0x2 (8 bytes)
  //        ioctls: const = 0x0 (8 bytes)
  //      }
  //    }
  //  ]
  *(uint64_t*)0x200000000080 = 0x200000ffd000;
  *(uint64_t*)0x200000000088 = 0x3000;
  *(uint64_t*)0x200000000090 = 2;
  *(uint64_t*)0x200000000098 = 0;
  syscall(__NR_ioctl, /*fd=*/r[0], /*cmd=*/0xc020aa00,
          /*arg=*/0x200000000080ul);
  //  ioctl$UFFDIO_WRITEPROTECT arguments: [
  //    fd: fd_uffd (resource)
  //    cmd: const = 0xc018aa06 (4 bytes)
  //    arg: ptr[in, uffdio_writeprotect] {
  //      uffdio_writeprotect {
  //        range: uffdio_range {
  //          start: VMA[0x2000]
  //          len: len = 0x2000 (8 bytes)
  //        }
  //        mode: uffdio_writeprotect_mode = 0x1 (8 bytes)
  //      }
  //    }
  //  ]
  *(uint64_t*)0x2000000000c0 = 0x200000ffe000;
  *(uint64_t*)0x2000000000c8 = 0x2000;
  *(uint64_t*)0x2000000000d0 = 1;
  syscall(__NR_ioctl, /*fd=*/r[0], /*cmd=*/0xc018aa06,
          /*arg=*/0x2000000000c0ul);
  //  ioctl$UFFDIO_REGISTER arguments: [
  //    fd: fd_uffd (resource)
  //    cmd: const = 0xc020aa00 (4 bytes)
  //    arg: ptr[in, uffdio_register] {
  //      uffdio_register {
  //        range: uffdio_range {
  //          start: VMA[0x3000]
  //          len: len = 0x3000 (8 bytes)
  //        }
  //        mode: uffdio_register_mode = 0x1 (8 bytes)
  //        ioctls: const = 0x0 (8 bytes)
  //      }
  //    }
  //  ]
  *(uint64_t*)0x200000000200 = 0x200000ffc000;
  *(uint64_t*)0x200000000208 = 0x3000;
  *(uint64_t*)0x200000000210 = 1;
  *(uint64_t*)0x200000000218 = 0;
  syscall(__NR_ioctl, /*fd=*/r[0], /*cmd=*/0xc020aa00,
          /*arg=*/0x200000000200ul);
  //  ioctl$UFFDIO_UNREGISTER arguments: [
  //    fd: fd_uffd (resource)
  //    cmd: const = 0x8010aa01 (4 bytes)
  //    arg: ptr[in, uffdio_range] {
  //      uffdio_range {
  //        start: VMA[0x3000]
  //        len: len = 0x3000 (8 bytes)
  //      }
  //    }
  //  ]
  *(uint64_t*)0x200000000240 = 0x200000ffb000;
  *(uint64_t*)0x200000000248 = 0x3000;
  syscall(__NR_ioctl, /*fd=*/r[0], /*cmd=*/0x8010aa01,
          /*arg=*/0x200000000240ul);
  //  mlock arguments: [
  //    addr: VMA[0x3000]
  //    size: len = 0x3000 (8 bytes)
  //  ]
  syscall(__NR_mlock, /*addr=*/0x200000ffd000ul, /*size=*/0x3000ul);
}
int main(void)
{
  syscall(__NR_mmap, /*addr=*/0x1ffffffff000ul, /*len=*/0x1000, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x200000000000ul, /*len=*/0x1000000,
          /*prot=PROT_WRITE|PROT_READ|PROT_EXEC*/ 7ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x200001000000ul, /*len=*/0x1000, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  const char* reason;
  (void)reason;
  if ((reason = setup_swap())) {
    fprintf(stderr, "reproducer setup failed: swap: %s\n", reason);
    exit(1);
  }
  use_temporary_dir();
  do_sandbox_none();
  return 0;
}
