// https://syzkaller.appspot.com/bug?id=26cb120b31cd24d984fc16da67f50fb375c432a7
// autogenerated by syzkaller (http://github.com/google/syzkaller)

#define _GNU_SOURCE
#include <endian.h>
#include <stdint.h>
#include <string.h>
#include <sys/syscall.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};
void loop()
{
  long res = 0;
  res = syscall(__NR_socket, 0xf, 3, 2);
  if (res != -1)
    r[0] = res;
  *(uint64_t*)0x20f56000 = 0;
  *(uint32_t*)0x20f56008 = 0;
  *(uint64_t*)0x20f56010 = 0x208feff0;
  *(uint64_t*)0x208feff0 = 0x20000080;
  memcpy((void*)0x20000080,
         "\x02\x03\x00\x02\x0e\x00\x00\x00\x00\x00\x00\x01\x02\x00\x00\x00\x04"
         "\x00\x08\x00\x05\x41\x24\xad\xec\x6b\x6a\x08\x8b\x00\x00\x1c\x00\x00"
         "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x00\x06"
         "\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x67\x00\x00\x00\x00"
         "\x00\xe1\x00\x00\x02\x00\x01\x00\x00\x00\x00\x00\x00\xd1\xfb\x02\x00"
         "\x00\x00\x00\x03\x00\x05\x00\x00\x00\x00\x00\x02\x00\x00\x00\xe0\x00"
         "\x00\x01\x00\x01\x00\x00\x00\x00\x00\x00",
         112);
  *(uint64_t*)0x208feff8 = 0x70;
  *(uint64_t*)0x20f56018 = 1;
  *(uint64_t*)0x20f56020 = 0;
  *(uint64_t*)0x20f56028 = 0;
  *(uint32_t*)0x20f56030 = 0;
  syscall(__NR_sendmsg, r[0], 0x20f56000, 0);
}

int main()
{
  syscall(__NR_mmap, 0x20000000, 0x1000000, 3, 0x32, -1, 0);
  loop();
  return 0;
}
