// https://syzkaller.appspot.com/bug?id=2b061d1fabd9760e98f92163543189b637c4af36
// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <endian.h>
#include <fcntl.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

static long syz_open_dev(long a0, long a1, long a2)
{
  if (a0 == 0xc || a0 == 0xb) {
    char buf[128];
    sprintf(buf, "/dev/%s/%d:%d", a0 == 0xc ? "char" : "block", (uint8_t)a1,
            (uint8_t)a2);
    return open(buf, O_RDWR, 0);
  } else {
    char buf[1024];
    char* hash;
    strncpy(buf, (char*)a0, sizeof(buf) - 1);
    buf[sizeof(buf) - 1] = 0;
    while ((hash = strchr(buf, '#'))) {
      *hash = '0' + (char)(a1 % 10);
      a1 /= 10;
    }
    return open(buf, a2, 0);
  }
}

uint64_t r[2] = {0xffffffffffffffff, 0xffffffffffffffff};

int main(void)
{
  syscall(__NR_mmap, 0x20000000, 0x1000000, 3, 0x32, -1, 0);
  long res = 0;
  memcpy((void*)0x20000000, "/dev/usbmon#", 13);
  res = syz_open_dev(0x20000000, 0, 0);
  if (res != -1)
    r[0] = res;
  memcpy((void*)0x20000040, "/dev/bus/usb/00#/00#", 21);
  syz_open_dev(0x20000040, 0x202, 0);
  syscall(__NR_pread64, r[0], 0x200003c0, 0x1000, 0);
  memcpy((void*)0x208be000, "/dev/usbmon#", 13);
  res = syz_open_dev(0x208be000, 0, 0);
  if (res != -1)
    r[1] = res;
  syscall(__NR_mmap, 0x20aba000, 0x1000, 0x1fffffd, 0x8011, r[1], 0);
  return 0;
}
