// https://syzkaller.appspot.com/bug?id=912f70e859dfffd2533b7cfcd2c71e0dd6f71e9d
// autogenerated by syzkaller (http://github.com/google/syzkaller)

#define _GNU_SOURCE
#include <arpa/inet.h>
#include <endian.h>
#include <errno.h>
#include <errno.h>
#include <fcntl.h>
#include <linux/if.h>
#include <linux/if_ether.h>
#include <linux/if_tun.h>
#include <linux/ip.h>
#include <linux/net.h>
#include <linux/tcp.h>
#include <net/if_arp.h>
#include <netinet/in.h>
#include <signal.h>
#include <stdarg.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/ioctl.h>
#include <sys/prctl.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/time.h>
#include <sys/uio.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

__attribute__((noreturn)) static void doexit(int status)
{
  volatile unsigned i;
  syscall(__NR_exit_group, status);
  for (i = 0;; i++) {
  }
}
#include <stdint.h>
#include <string.h>

const int kFailStatus = 67;
const int kRetryStatus = 69;

static void fail(const char* msg, ...)
{
  int e = errno;
  va_list args;
  va_start(args, msg);
  vfprintf(stderr, msg, args);
  va_end(args);
  fprintf(stderr, " (errno %d)\n", e);
  doexit((e == ENOMEM || e == EAGAIN) ? kRetryStatus : kFailStatus);
}

#define BITMASK_LEN(type, bf_len) (type)((1ull << (bf_len)) - 1)

#define BITMASK_LEN_OFF(type, bf_off, bf_len)                                  \
  (type)(BITMASK_LEN(type, (bf_len)) << (bf_off))

#define STORE_BY_BITMASK(type, addr, val, bf_off, bf_len)                      \
  if ((bf_off) == 0 && (bf_len) == 0) {                                        \
    *(type*)(addr) = (type)(val);                                              \
  } else {                                                                     \
    type new_val = *(type*)(addr);                                             \
    new_val &= ~BITMASK_LEN_OFF(type, (bf_off), (bf_len));                     \
    new_val |= ((type)(val)&BITMASK_LEN(type, (bf_len))) << (bf_off);          \
    *(type*)(addr) = new_val;                                                  \
  }

struct csum_inet {
  uint32_t acc;
};

static void csum_inet_init(struct csum_inet* csum)
{
  csum->acc = 0;
}

static void csum_inet_update(struct csum_inet* csum, const uint8_t* data,
                             size_t length)
{
  if (length == 0)
    return;

  size_t i;
  for (i = 0; i < length - 1; i += 2)
    csum->acc += *(uint16_t*)&data[i];

  if (length & 1)
    csum->acc += (uint16_t)data[length - 1];

  while (csum->acc > 0xffff)
    csum->acc = (csum->acc & 0xffff) + (csum->acc >> 16);
}

static uint16_t csum_inet_digest(struct csum_inet* csum)
{
  return ~csum->acc;
}

static uint64_t current_time_ms()
{
  struct timespec ts;

  if (clock_gettime(CLOCK_MONOTONIC, &ts))
    fail("clock_gettime failed");
  return (uint64_t)ts.tv_sec * 1000 + (uint64_t)ts.tv_nsec / 1000000;
}

static void vsnprintf_check(char* str, size_t size, const char* format,
                            va_list args)
{
  int rv;

  rv = vsnprintf(str, size, format, args);
  if (rv < 0)
    fail("tun: snprintf failed");
  if ((size_t)rv >= size)
    fail("tun: string '%s...' doesn't fit into buffer", str);
}

static void snprintf_check(char* str, size_t size, const char* format, ...)
{
  va_list args;

  va_start(args, format);
  vsnprintf_check(str, size, format, args);
  va_end(args);
}

#define COMMAND_MAX_LEN 128
#define PATH_PREFIX                                                            \
  "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin "
#define PATH_PREFIX_LEN (sizeof(PATH_PREFIX) - 1)

static void execute_command(bool panic, const char* format, ...)
{
  va_list args;
  char command[PATH_PREFIX_LEN + COMMAND_MAX_LEN];
  int rv;

  va_start(args, format);
  memcpy(command, PATH_PREFIX, PATH_PREFIX_LEN);
  vsnprintf_check(command + PATH_PREFIX_LEN, COMMAND_MAX_LEN, format, args);
  rv = system(command);
  if (panic && rv != 0)
    fail("tun: command \"%s\" failed with code %d", &command[0], rv);

  va_end(args);
}

static int tunfd = -1;
static int tun_frags_enabled;

#define SYZ_TUN_MAX_PACKET_SIZE 1000

#define MAX_PIDS 32
#define ADDR_MAX_LEN 32

#define LOCAL_MAC "aa:aa:aa:aa:%02hx:aa"
#define REMOTE_MAC "aa:aa:aa:aa:%02hx:bb"

#define LOCAL_IPV4 "172.20.%d.170"
#define REMOTE_IPV4 "172.20.%d.187"

#define LOCAL_IPV6 "fe80::%02hx:aa"
#define REMOTE_IPV6 "fe80::%02hx:bb"

#define IFF_NAPI 0x0010
#define IFF_NAPI_FRAGS 0x0020

static void initialize_tun(int id)
{
  if (id >= MAX_PIDS)
    fail("tun: no more than %d executors", MAX_PIDS);

  tunfd = open("/dev/net/tun", O_RDWR | O_NONBLOCK);
  if (tunfd == -1) {
    printf("tun: can't open /dev/net/tun: please enable CONFIG_TUN=y\n");
    printf("otherwise fuzzing or reproducing might not work as intended\n");
    return;
  }

  char iface[IFNAMSIZ];
  snprintf_check(iface, sizeof(iface), "syz%d", id);

  struct ifreq ifr;
  memset(&ifr, 0, sizeof(ifr));
  strncpy(ifr.ifr_name, iface, IFNAMSIZ);
  ifr.ifr_flags = IFF_TAP | IFF_NO_PI | IFF_NAPI | IFF_NAPI_FRAGS;
  if (ioctl(tunfd, TUNSETIFF, (void*)&ifr) < 0) {
    ifr.ifr_flags = IFF_TAP | IFF_NO_PI;
    if (ioctl(tunfd, TUNSETIFF, (void*)&ifr) < 0)
      fail("tun: ioctl(TUNSETIFF) failed");
  }
  if (ioctl(tunfd, TUNGETIFF, (void*)&ifr) < 0)
    fail("tun: ioctl(TUNGETIFF) failed");
  tun_frags_enabled = (ifr.ifr_flags & IFF_NAPI_FRAGS) != 0;

  char local_mac[ADDR_MAX_LEN];
  snprintf_check(local_mac, sizeof(local_mac), LOCAL_MAC, id);
  char remote_mac[ADDR_MAX_LEN];
  snprintf_check(remote_mac, sizeof(remote_mac), REMOTE_MAC, id);

  char local_ipv4[ADDR_MAX_LEN];
  snprintf_check(local_ipv4, sizeof(local_ipv4), LOCAL_IPV4, id);
  char remote_ipv4[ADDR_MAX_LEN];
  snprintf_check(remote_ipv4, sizeof(remote_ipv4), REMOTE_IPV4, id);

  char local_ipv6[ADDR_MAX_LEN];
  snprintf_check(local_ipv6, sizeof(local_ipv6), LOCAL_IPV6, id);
  char remote_ipv6[ADDR_MAX_LEN];
  snprintf_check(remote_ipv6, sizeof(remote_ipv6), REMOTE_IPV6, id);

  execute_command(1, "sysctl -w net.ipv6.conf.%s.accept_dad=0", iface);

  execute_command(1, "sysctl -w net.ipv6.conf.%s.router_solicitations=0",
                  iface);

  execute_command(1, "ip link set dev %s address %s", iface, local_mac);
  execute_command(1, "ip addr add %s/24 dev %s", local_ipv4, iface);
  execute_command(1, "ip -6 addr add %s/120 dev %s", local_ipv6, iface);
  execute_command(1, "ip neigh add %s lladdr %s dev %s nud permanent",
                  remote_ipv4, remote_mac, iface);
  execute_command(1, "ip -6 neigh add %s lladdr %s dev %s nud permanent",
                  remote_ipv6, remote_mac, iface);
  execute_command(1, "ip link set dev %s up", iface);
}

#define DEV_IPV4 "172.20.%d.%d"
#define DEV_IPV6 "fe80::%02hx:%02hx"
#define DEV_MAC "aa:aa:aa:aa:%02hx:%02hx"

static void initialize_netdevices(int id)
{
  unsigned i;
  const char* devtypes[] = {"ip6gretap", "bridge", "vcan"};
  const char* devnames[] = {"lo",       "sit0",    "bridge0", "vcan0",
                            "tunl0",    "gre0",    "gretap0", "ip_vti0",
                            "ip6_vti0", "ip6tnl0", "ip6gre0", "ip6gretap0",
                            "erspan0"};

  for (i = 0; i < sizeof(devtypes) / (sizeof(devtypes[0])); i++)
    execute_command(0, "ip link add dev %s0 type %s", devtypes[i], devtypes[i]);
  for (i = 0; i < sizeof(devnames) / (sizeof(devnames[0])); i++) {
    char addr[ADDR_MAX_LEN];
    snprintf_check(addr, sizeof(addr), DEV_IPV4, id, id + 10);
    execute_command(0, "ip -4 addr add %s/24 dev %s", addr, devnames[i]);
    snprintf_check(addr, sizeof(addr), DEV_IPV6, id, id + 10);
    execute_command(0, "ip -6 addr add %s/120 dev %s", addr, devnames[i]);
    snprintf_check(addr, sizeof(addr), DEV_MAC, id, id + 10);
    execute_command(0, "ip link set dev %s address %s", devnames[i], addr);
    execute_command(0, "ip link set dev %s up", devnames[i]);
  }
}

static void setup_tun(uint64_t pid, bool enable_tun)
{
  if (enable_tun) {
    initialize_tun(pid);
    initialize_netdevices(pid);
  }
}

static int read_tun(char* data, int size)
{
  if (tunfd < 0)
    return -1;

  int rv = read(tunfd, data, size);
  if (rv < 0) {
    if (errno == EAGAIN)
      return -1;
    if (errno == EBADFD)
      return -1;
    fail("tun: read failed with %d", rv);
  }
  return rv;
}

#define MAX_FRAGS 4
struct vnet_fragmentation {
  uint32_t full;
  uint32_t count;
  uint32_t frags[MAX_FRAGS];
};

static uintptr_t syz_emit_ethernet(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
  if (tunfd < 0)
    return (uintptr_t)-1;

  uint32_t length = a0;
  char* data = (char*)a1;

  struct vnet_fragmentation* frags = (struct vnet_fragmentation*)a2;
  struct iovec vecs[MAX_FRAGS + 1];
  uint32_t nfrags = 0;
  if (!tun_frags_enabled || frags == NULL) {
    vecs[nfrags].iov_base = data;
    vecs[nfrags].iov_len = length;
    nfrags++;
  } else {
    bool full = true;
    uint32_t i, count = 0;
    full = frags->full;
    count = frags->count;
    if (count > MAX_FRAGS)
      count = MAX_FRAGS;
    for (i = 0; i < count && length != 0; i++) {
      uint32_t size = 0;
      size = frags->frags[i];
      if (size > length)
        size = length;
      vecs[nfrags].iov_base = data;
      vecs[nfrags].iov_len = size;
      nfrags++;
      data += size;
      length -= size;
    }
    if (length != 0 && (full || nfrags == 0)) {
      vecs[nfrags].iov_base = data;
      vecs[nfrags].iov_len = length;
      nfrags++;
    }
  }
  return writev(tunfd, vecs, nfrags);
}

static void flush_tun()
{
  char data[SYZ_TUN_MAX_PACKET_SIZE];
  while (read_tun(&data[0], sizeof(data)) != -1)
    ;
}

struct ipt_getinfo {
  char name[32];
  unsigned int valid_hooks;
  unsigned int hook_entry[5];
  unsigned int underflow[5];
  unsigned int num_entries;
  unsigned int size;
};

struct ipt_get_entries {
  char name[32];
  unsigned int size;
  void* entrytable[1024 / sizeof(void*)];
};

struct xt_counters {
  uint64_t pcnt, bcnt;
};

struct ipt_replace {
  char name[32];
  unsigned int valid_hooks;
  unsigned int num_entries;
  unsigned int size;
  unsigned int hook_entry[5];
  unsigned int underflow[5];
  unsigned int num_counters;
  struct xt_counters* counters;
  char entrytable[1024];
};

struct ipt_table_desc {
  const char* name;
  struct ipt_getinfo info;
  struct ipt_get_entries entries;
  struct ipt_replace replace;
  struct xt_counters counters[10];
};

static struct ipt_table_desc ipv4_tables[] = {
    {.name = "filter"}, {.name = "nat"},      {.name = "mangle"},
    {.name = "raw"},    {.name = "security"},
};

#define IPT_BASE_CTL 64
#define IPT_SO_SET_REPLACE (IPT_BASE_CTL)
#define IPT_SO_GET_INFO (IPT_BASE_CTL)
#define IPT_SO_GET_ENTRIES (IPT_BASE_CTL + 1)

static void checkpoint_net_namespace(void)
{
  socklen_t optlen;
  unsigned i;
  int fd;

  fd = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
  if (fd == -1)
    fail("socket(AF_INET, SOCK_STREAM, IPPROTO_TCP)");
  for (i = 0; i < sizeof(ipv4_tables) / sizeof(ipv4_tables[0]); i++) {
    struct ipt_table_desc* table = &ipv4_tables[i];
    strcpy(table->info.name, table->name);
    strcpy(table->entries.name, table->name);
    strcpy(table->replace.name, table->name);
    optlen = sizeof(table->info);
    if (getsockopt(fd, SOL_IP, IPT_SO_GET_INFO, &table->info, &optlen)) {
      switch (errno) {
      case EPERM:
      case ENOENT:
      case ENOPROTOOPT:
        continue;
      }
      fail("getsockopt(IPT_SO_GET_INFO)");
    }
    if (table->info.size > sizeof(table->entries.entrytable))
      fail("table size is too large: %u", table->info.size);
    if (table->info.num_entries >
        sizeof(table->counters) / sizeof(table->counters[0]))
      fail("too many counters: %u", table->info.num_entries);
    table->entries.size = table->info.size;
    optlen = sizeof(table->entries) - sizeof(table->entries.entrytable) +
             table->info.size;
    if (getsockopt(fd, SOL_IP, IPT_SO_GET_ENTRIES, &table->entries, &optlen))
      fail("getsockopt(IPT_SO_GET_ENTRIES)");
    table->replace.valid_hooks = table->info.valid_hooks;
    table->replace.num_entries = table->info.num_entries;
    table->replace.counters = table->counters;
    table->replace.size = table->info.size;
    memcpy(table->replace.hook_entry, table->info.hook_entry,
           sizeof(table->replace.hook_entry));
    memcpy(table->replace.underflow, table->info.underflow,
           sizeof(table->replace.underflow));
    memcpy(table->replace.entrytable, table->entries.entrytable,
           table->info.size);
  }
  close(fd);
}

static void reset_net_namespace(void)
{
  struct ipt_get_entries entries;
  struct ipt_getinfo info;
  socklen_t optlen;
  unsigned i;
  int fd;

  memset(&info, 0, sizeof(info));
  memset(&entries, 0, sizeof(entries));
  fd = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
  if (fd == -1)
    fail("socket(AF_INET, SOCK_STREAM, IPPROTO_TCP)");
  for (i = 0; i < sizeof(ipv4_tables) / sizeof(ipv4_tables[0]); i++) {
    struct ipt_table_desc* table = &ipv4_tables[i];
    if (table->info.valid_hooks == 0)
      continue;
    strcpy(info.name, table->name);
    optlen = sizeof(info);
    if (getsockopt(fd, SOL_IP, IPT_SO_GET_INFO, &info, &optlen))
      fail("getsockopt(IPT_SO_GET_INFO)");
    if (memcmp(&table->info, &info, sizeof(table->info)) == 0) {
      strcpy(entries.name, table->name);
      entries.size = table->info.size;
      optlen = sizeof(entries) - sizeof(entries.entrytable) + entries.size;
      if (getsockopt(fd, SOL_IP, IPT_SO_GET_ENTRIES, &entries, &optlen))
        fail("getsockopt(IPT_SO_GET_ENTRIES)");
      if (memcmp(&table->entries, &entries, optlen) == 0)
        continue;
    }
    table->replace.num_counters = info.num_entries;
    optlen = sizeof(table->replace) - sizeof(table->replace.entrytable) +
             table->replace.size;
    if (setsockopt(fd, SOL_IP, IPT_SO_SET_REPLACE, &table->replace, optlen))
      fail("setsockopt(IPT_SO_SET_REPLACE)");
  }
  close(fd);
}

static void test();

void loop()
{
  int iter;
  checkpoint_net_namespace();
  for (iter = 0;; iter++) {
    int pid = fork();
    if (pid < 0)
      fail("loop fork failed");
    if (pid == 0) {
      prctl(PR_SET_PDEATHSIG, SIGKILL, 0, 0, 0);
      setpgrp();
      flush_tun();
      test();
      doexit(0);
    }
    int status = 0;
    uint64_t start = current_time_ms();
    for (;;) {
      int res = waitpid(-1, &status, __WALL | WNOHANG);
      if (res == pid)
        break;
      usleep(1000);
      if (current_time_ms() - start > 5 * 1000) {
        kill(-pid, SIGKILL);
        kill(pid, SIGKILL);
        while (waitpid(-1, &status, __WALL) != pid) {
        }
        break;
      }
    }
    reset_net_namespace();
  }
}

long r[3];
void test()
{
  memset(r, -1, sizeof(r));
  syscall(__NR_mmap, 0x20000000, 0xfff000, 3, 0x32, -1, 0);
  r[0] = syscall(__NR_socket, 0xa, 2, 0);
  memcpy((void*)0x20007000, "\x72\x61\x77\x00\x00\x00\x00\x00\x00\x00\x00\x00"
                            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
                            "\x00\x00\x00\x00\x00\x00\x00\x00",
         32);
  *(uint32_t*)0x20007020 = 9;
  *(uint32_t*)0x20007024 = 4;
  *(uint32_t*)0x20007028 = 0x3a8;
  *(uint32_t*)0x2000702c = 0;
  *(uint32_t*)0x20007030 = -1;
  *(uint32_t*)0x20007034 = -1;
  *(uint32_t*)0x20007038 = 0;
  *(uint32_t*)0x2000703c = -1;
  *(uint32_t*)0x20007040 = 0;
  *(uint32_t*)0x20007044 = -1;
  *(uint32_t*)0x20007048 = -1;
  *(uint32_t*)0x2000704c = 0;
  *(uint32_t*)0x20007050 = -1;
  *(uint32_t*)0x20007054 = 4;
  *(uint64_t*)0x20007058 = 0x20004000;
  *(uint8_t*)0x20007060 = 0;
  *(uint8_t*)0x20007061 = 0;
  *(uint8_t*)0x20007062 = 0;
  *(uint8_t*)0x20007063 = 0;
  *(uint8_t*)0x20007064 = 0;
  *(uint8_t*)0x20007065 = 0;
  *(uint8_t*)0x20007066 = 0;
  *(uint8_t*)0x20007067 = 0;
  *(uint8_t*)0x20007068 = 0;
  *(uint8_t*)0x20007069 = 0;
  *(uint8_t*)0x2000706a = 0;
  *(uint8_t*)0x2000706b = 0;
  *(uint8_t*)0x2000706c = 0;
  *(uint8_t*)0x2000706d = 0;
  *(uint8_t*)0x2000706e = 0;
  *(uint8_t*)0x2000706f = 0;
  *(uint8_t*)0x20007070 = 0;
  *(uint8_t*)0x20007071 = 0;
  *(uint8_t*)0x20007072 = 0;
  *(uint8_t*)0x20007073 = 0;
  *(uint8_t*)0x20007074 = 0;
  *(uint8_t*)0x20007075 = 0;
  *(uint8_t*)0x20007076 = 0;
  *(uint8_t*)0x20007077 = 0;
  *(uint8_t*)0x20007078 = 0;
  *(uint8_t*)0x20007079 = 0;
  *(uint8_t*)0x2000707a = 0;
  *(uint8_t*)0x2000707b = 0;
  *(uint8_t*)0x2000707c = 0;
  *(uint8_t*)0x2000707d = 0;
  *(uint8_t*)0x2000707e = 0;
  *(uint8_t*)0x2000707f = 0;
  *(uint8_t*)0x20007080 = 0;
  *(uint8_t*)0x20007081 = 0;
  *(uint8_t*)0x20007082 = 0;
  *(uint8_t*)0x20007083 = 0;
  *(uint8_t*)0x20007084 = 0;
  *(uint8_t*)0x20007085 = 0;
  *(uint8_t*)0x20007086 = 0;
  *(uint8_t*)0x20007087 = 0;
  *(uint8_t*)0x20007088 = 0;
  *(uint8_t*)0x20007089 = 0;
  *(uint8_t*)0x2000708a = 0;
  *(uint8_t*)0x2000708b = 0;
  *(uint8_t*)0x2000708c = 0;
  *(uint8_t*)0x2000708d = 0;
  *(uint8_t*)0x2000708e = 0;
  *(uint8_t*)0x2000708f = 0;
  *(uint8_t*)0x20007090 = 0;
  *(uint8_t*)0x20007091 = 0;
  *(uint8_t*)0x20007092 = 0;
  *(uint8_t*)0x20007093 = 0;
  *(uint8_t*)0x20007094 = 0;
  *(uint8_t*)0x20007095 = 0;
  *(uint8_t*)0x20007096 = 0;
  *(uint8_t*)0x20007097 = 0;
  *(uint8_t*)0x20007098 = 0;
  *(uint8_t*)0x20007099 = 0;
  *(uint8_t*)0x2000709a = 0;
  *(uint8_t*)0x2000709b = 0;
  *(uint8_t*)0x2000709c = 0;
  *(uint8_t*)0x2000709d = 0;
  *(uint8_t*)0x2000709e = 0;
  *(uint8_t*)0x2000709f = 0;
  *(uint8_t*)0x200070a0 = 0;
  *(uint8_t*)0x200070a1 = 0;
  *(uint8_t*)0x200070a2 = 0;
  *(uint8_t*)0x200070a3 = 0;
  *(uint8_t*)0x200070a4 = 0;
  *(uint8_t*)0x200070a5 = 0;
  *(uint8_t*)0x200070a6 = 0;
  *(uint8_t*)0x200070a7 = 0;
  *(uint8_t*)0x200070a8 = 0;
  *(uint8_t*)0x200070a9 = 0;
  *(uint8_t*)0x200070aa = 0;
  *(uint8_t*)0x200070ab = 0;
  *(uint8_t*)0x200070ac = 0;
  *(uint8_t*)0x200070ad = 0;
  *(uint8_t*)0x200070ae = 0;
  *(uint8_t*)0x200070af = 0;
  *(uint8_t*)0x200070b0 = 0;
  *(uint8_t*)0x200070b1 = 0;
  *(uint8_t*)0x200070b2 = 0;
  *(uint8_t*)0x200070b3 = 0;
  *(uint8_t*)0x200070b4 = 0;
  *(uint8_t*)0x200070b5 = 0;
  *(uint8_t*)0x200070b6 = 0;
  *(uint8_t*)0x200070b7 = 0;
  *(uint8_t*)0x200070b8 = 0;
  *(uint8_t*)0x200070b9 = 0;
  *(uint8_t*)0x200070ba = 0;
  *(uint8_t*)0x200070bb = 0;
  *(uint8_t*)0x200070bc = 0;
  *(uint8_t*)0x200070bd = 0;
  *(uint8_t*)0x200070be = 0;
  *(uint8_t*)0x200070bf = 0;
  *(uint8_t*)0x200070c0 = 0;
  *(uint8_t*)0x200070c1 = 0;
  *(uint8_t*)0x200070c2 = 0;
  *(uint8_t*)0x200070c3 = 0;
  *(uint8_t*)0x200070c4 = 0;
  *(uint8_t*)0x200070c5 = 0;
  *(uint8_t*)0x200070c6 = 0;
  *(uint8_t*)0x200070c7 = 0;
  *(uint8_t*)0x200070c8 = 0;
  *(uint8_t*)0x200070c9 = 0;
  *(uint8_t*)0x200070ca = 0;
  *(uint8_t*)0x200070cb = 0;
  *(uint8_t*)0x200070cc = 0;
  *(uint8_t*)0x200070cd = 0;
  *(uint8_t*)0x200070ce = 0;
  *(uint8_t*)0x200070cf = 0;
  *(uint8_t*)0x200070d0 = 0;
  *(uint8_t*)0x200070d1 = 0;
  *(uint8_t*)0x200070d2 = 0;
  *(uint8_t*)0x200070d3 = 0;
  *(uint8_t*)0x200070d4 = 0;
  *(uint8_t*)0x200070d5 = 0;
  *(uint8_t*)0x200070d6 = 0;
  *(uint8_t*)0x200070d7 = 0;
  *(uint8_t*)0x200070d8 = 0;
  *(uint8_t*)0x200070d9 = 0;
  *(uint8_t*)0x200070da = 0;
  *(uint8_t*)0x200070db = 0;
  *(uint8_t*)0x200070dc = 0;
  *(uint8_t*)0x200070dd = 0;
  *(uint8_t*)0x200070de = 0;
  *(uint8_t*)0x200070df = 0;
  *(uint8_t*)0x200070e0 = 0;
  *(uint8_t*)0x200070e1 = 0;
  *(uint8_t*)0x200070e2 = 0;
  *(uint8_t*)0x200070e3 = 0;
  *(uint8_t*)0x200070e4 = 0;
  *(uint8_t*)0x200070e5 = 0;
  *(uint8_t*)0x200070e6 = 0;
  *(uint8_t*)0x200070e7 = 0;
  *(uint32_t*)0x200070e8 = 0;
  *(uint16_t*)0x200070ec = 0xa8;
  *(uint16_t*)0x200070ee = 0xd0;
  *(uint32_t*)0x200070f0 = 0;
  *(uint64_t*)0x200070f8 = 0;
  *(uint64_t*)0x20007100 = 0;
  *(uint16_t*)0x20007108 = 0x28;
  memcpy((void*)0x2000710a, "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
                            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
                            "\x00\x00\x00\x00\x00",
         29);
  *(uint8_t*)0x20007127 = 0;
  *(uint32_t*)0x20007128 = 0xfffffffe;
  *(uint8_t*)0x20007130 = 0xfe;
  *(uint8_t*)0x20007131 = 0x80;
  *(uint8_t*)0x20007132 = 0;
  *(uint8_t*)0x20007133 = 0;
  *(uint8_t*)0x20007134 = 0;
  *(uint8_t*)0x20007135 = 0;
  *(uint8_t*)0x20007136 = 0;
  *(uint8_t*)0x20007137 = 0;
  *(uint8_t*)0x20007138 = 0;
  *(uint8_t*)0x20007139 = 0;
  *(uint8_t*)0x2000713a = 0;
  *(uint8_t*)0x2000713b = 0;
  *(uint8_t*)0x2000713c = 0;
  *(uint8_t*)0x2000713d = 0;
  *(uint8_t*)0x2000713e = 0;
  *(uint8_t*)0x2000713f = 0xaa;
  *(uint8_t*)0x20007140 = -1;
  *(uint8_t*)0x20007141 = 1;
  *(uint8_t*)0x20007142 = 0;
  *(uint8_t*)0x20007143 = 0;
  *(uint8_t*)0x20007144 = 0;
  *(uint8_t*)0x20007145 = 0;
  *(uint8_t*)0x20007146 = 0;
  *(uint8_t*)0x20007147 = 0;
  *(uint8_t*)0x20007148 = 0;
  *(uint8_t*)0x20007149 = 0;
  *(uint8_t*)0x2000714a = 0;
  *(uint8_t*)0x2000714b = 0;
  *(uint8_t*)0x2000714c = 0;
  *(uint8_t*)0x2000714d = 0;
  *(uint8_t*)0x2000714e = 0;
  *(uint8_t*)0x2000714f = 1;
  *(uint32_t*)0x20007150 = htobe32(0);
  *(uint32_t*)0x20007154 = htobe32(0);
  *(uint32_t*)0x20007158 = htobe32(0);
  *(uint32_t*)0x2000715c = htobe32(0);
  *(uint32_t*)0x20007160 = htobe32(0);
  *(uint32_t*)0x20007164 = htobe32(0);
  *(uint32_t*)0x20007168 = htobe32(0);
  *(uint32_t*)0x2000716c = htobe32(0);
  *(uint8_t*)0x20007170 = 0x73;
  *(uint8_t*)0x20007171 = 0x79;
  *(uint8_t*)0x20007172 = 0x7a;
  *(uint8_t*)0x20007173 = 0;
  *(uint8_t*)0x20007174 = 0;
  memcpy((void*)0x20007180,
         "\x69\x66\x62\x30\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00",
         16);
  *(uint8_t*)0x20007190 = 0;
  *(uint8_t*)0x20007191 = 0;
  *(uint8_t*)0x20007192 = 0;
  *(uint8_t*)0x20007193 = 0;
  *(uint8_t*)0x20007194 = 0;
  *(uint8_t*)0x20007195 = 0;
  *(uint8_t*)0x20007196 = 0;
  *(uint8_t*)0x20007197 = 0;
  *(uint8_t*)0x20007198 = 0;
  *(uint8_t*)0x20007199 = 0;
  *(uint8_t*)0x2000719a = 0;
  *(uint8_t*)0x2000719b = 0;
  *(uint8_t*)0x2000719c = 0;
  *(uint8_t*)0x2000719d = 0;
  *(uint8_t*)0x2000719e = 0;
  *(uint8_t*)0x2000719f = 0;
  *(uint8_t*)0x200071a0 = 0;
  *(uint8_t*)0x200071a1 = 0;
  *(uint8_t*)0x200071a2 = 0;
  *(uint8_t*)0x200071a3 = 0;
  *(uint8_t*)0x200071a4 = 0;
  *(uint8_t*)0x200071a5 = 0;
  *(uint8_t*)0x200071a6 = 0;
  *(uint8_t*)0x200071a7 = 0;
  *(uint8_t*)0x200071a8 = 0;
  *(uint8_t*)0x200071a9 = 0;
  *(uint8_t*)0x200071aa = 0;
  *(uint8_t*)0x200071ab = 0;
  *(uint8_t*)0x200071ac = 0;
  *(uint8_t*)0x200071ad = 0;
  *(uint8_t*)0x200071ae = 0;
  *(uint8_t*)0x200071af = 0;
  *(uint16_t*)0x200071b0 = 0;
  *(uint8_t*)0x200071b2 = 0;
  *(uint8_t*)0x200071b3 = 0;
  *(uint8_t*)0x200071b4 = 0;
  *(uint32_t*)0x200071b8 = 0;
  *(uint16_t*)0x200071bc = 0xa8;
  *(uint16_t*)0x200071be = 0xd8;
  *(uint32_t*)0x200071c0 = 0;
  *(uint64_t*)0x200071c4 = 0;
  *(uint64_t*)0x200071cc = 0;
  *(uint16_t*)0x200071d8 = 0x30;
  memcpy((void*)0x200071da, "\x43\x4f\x4e\x4e\x4d\x41\x52\x4b\x00\x00\x00\x00"
                            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
                            "\x00\x00\x00\x00\x00",
         29);
  *(uint8_t*)0x200071f7 = 1;
  *(uint32_t*)0x200071f8 = 0;
  *(uint32_t*)0x200071fc = 0;
  *(uint32_t*)0x20007200 = 0;
  *(uint8_t*)0x20007204 = 0;
  *(uint8_t*)0x20007208 = 0xfe;
  *(uint8_t*)0x20007209 = 0x80;
  *(uint8_t*)0x2000720a = 0;
  *(uint8_t*)0x2000720b = 0;
  *(uint8_t*)0x2000720c = 0;
  *(uint8_t*)0x2000720d = 0;
  *(uint8_t*)0x2000720e = 0;
  *(uint8_t*)0x2000720f = 0;
  *(uint8_t*)0x20007210 = 0;
  *(uint8_t*)0x20007211 = 0;
  *(uint8_t*)0x20007212 = 0;
  *(uint8_t*)0x20007213 = 0;
  *(uint8_t*)0x20007214 = 0;
  *(uint8_t*)0x20007215 = 0;
  *(uint8_t*)0x20007216 = 0;
  *(uint8_t*)0x20007217 = 0;
  *(uint8_t*)0x20007218 = 0xfe;
  *(uint8_t*)0x20007219 = 0x80;
  *(uint8_t*)0x2000721a = 0;
  *(uint8_t*)0x2000721b = 0;
  *(uint8_t*)0x2000721c = 0;
  *(uint8_t*)0x2000721d = 0;
  *(uint8_t*)0x2000721e = 0;
  *(uint8_t*)0x2000721f = 0;
  *(uint8_t*)0x20007220 = 0;
  *(uint8_t*)0x20007221 = 0;
  *(uint8_t*)0x20007222 = 0;
  *(uint8_t*)0x20007223 = 0;
  *(uint8_t*)0x20007224 = 0;
  *(uint8_t*)0x20007225 = 0;
  *(uint8_t*)0x20007226 = 0;
  *(uint8_t*)0x20007227 = 0xbb;
  *(uint32_t*)0x20007228 = htobe32(0);
  *(uint32_t*)0x2000722c = htobe32(0);
  *(uint32_t*)0x20007230 = htobe32(0);
  *(uint32_t*)0x20007234 = htobe32(0);
  *(uint32_t*)0x20007238 = htobe32(0);
  *(uint32_t*)0x2000723c = htobe32(0);
  *(uint32_t*)0x20007240 = htobe32(0);
  *(uint32_t*)0x20007244 = htobe32(0);
  memcpy((void*)0x20007248,
         "\x69\x70\x36\x67\x72\x65\x74\x61\x70\x30\x00\x00\x00\x00\x00\x00",
         16);
  *(uint8_t*)0x20007258 = 0x73;
  *(uint8_t*)0x20007259 = 0x79;
  *(uint8_t*)0x2000725a = 0x7a;
  *(uint8_t*)0x2000725b = 0;
  *(uint8_t*)0x2000725c = 0;
  *(uint8_t*)0x20007268 = -1;
  *(uint8_t*)0x20007269 = 0;
  *(uint8_t*)0x2000726a = 0;
  *(uint8_t*)0x2000726b = 0;
  *(uint8_t*)0x2000726c = 0;
  *(uint8_t*)0x2000726d = 0;
  *(uint8_t*)0x2000726e = 0;
  *(uint8_t*)0x2000726f = 0;
  *(uint8_t*)0x20007270 = 0;
  *(uint8_t*)0x20007271 = 0;
  *(uint8_t*)0x20007272 = 0;
  *(uint8_t*)0x20007273 = 0;
  *(uint8_t*)0x20007274 = 0;
  *(uint8_t*)0x20007275 = 0;
  *(uint8_t*)0x20007276 = 0;
  *(uint8_t*)0x20007277 = 0;
  *(uint8_t*)0x20007278 = 0;
  *(uint8_t*)0x20007279 = 0;
  *(uint8_t*)0x2000727a = 0;
  *(uint8_t*)0x2000727b = 0;
  *(uint8_t*)0x2000727c = 0;
  *(uint8_t*)0x2000727d = 0;
  *(uint8_t*)0x2000727e = 0;
  *(uint8_t*)0x2000727f = 0;
  *(uint8_t*)0x20007280 = 0;
  *(uint8_t*)0x20007281 = 0;
  *(uint8_t*)0x20007282 = 0;
  *(uint8_t*)0x20007283 = 0;
  *(uint8_t*)0x20007284 = 0;
  *(uint8_t*)0x20007285 = 0;
  *(uint8_t*)0x20007286 = 0;
  *(uint8_t*)0x20007287 = 0;
  *(uint16_t*)0x20007288 = 0x84;
  *(uint8_t*)0x2000728a = 0;
  *(uint8_t*)0x2000728b = 0;
  *(uint8_t*)0x2000728c = 0;
  *(uint32_t*)0x20007290 = 0;
  *(uint16_t*)0x20007294 = 0xa8;
  *(uint16_t*)0x20007296 = 0xf0;
  *(uint32_t*)0x20007298 = 0;
  *(uint64_t*)0x2000729c = 0;
  *(uint64_t*)0x200072a4 = 0;
  *(uint16_t*)0x200072b0 = 0x48;
  memcpy((void*)0x200072b2, "\x43\x54\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
                            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
                            "\x00\x00\x00\x00\x00",
         29);
  *(uint8_t*)0x200072cf = 0;
  *(uint16_t*)0x200072d0 = 0;
  *(uint16_t*)0x200072d2 = 0;
  *(uint32_t*)0x200072d4 = 0;
  *(uint32_t*)0x200072d8 = 0;
  memcpy((void*)0x200072dc,
         "\x70\x70\x74\x70\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00",
         16);
  *(uint64_t*)0x200072f0 = 0;
  *(uint8_t*)0x200072f8 = 0xfe;
  *(uint8_t*)0x200072f9 = 0x80;
  *(uint8_t*)0x200072fa = 0;
  *(uint8_t*)0x200072fb = 0;
  *(uint8_t*)0x200072fc = 0;
  *(uint8_t*)0x200072fd = 0;
  *(uint8_t*)0x200072fe = 0;
  *(uint8_t*)0x200072ff = 0;
  *(uint8_t*)0x20007300 = 0;
  *(uint8_t*)0x20007301 = 0;
  *(uint8_t*)0x20007302 = 0;
  *(uint8_t*)0x20007303 = 0;
  *(uint8_t*)0x20007304 = 0;
  *(uint8_t*)0x20007305 = 0;
  *(uint8_t*)0x20007306 = 0;
  *(uint8_t*)0x20007307 = 0;
  *(uint8_t*)0x20007308 = 0;
  *(uint8_t*)0x20007309 = 0;
  *(uint8_t*)0x2000730a = 0;
  *(uint8_t*)0x2000730b = 0;
  *(uint8_t*)0x2000730c = 0;
  *(uint8_t*)0x2000730d = 0;
  *(uint8_t*)0x2000730e = 0;
  *(uint8_t*)0x2000730f = 0;
  *(uint8_t*)0x20007310 = 0;
  *(uint8_t*)0x20007311 = 0;
  *(uint8_t*)0x20007312 = -1;
  *(uint8_t*)0x20007313 = -1;
  *(uint8_t*)0x20007314 = 0xac;
  *(uint8_t*)0x20007315 = 0x14;
  *(uint8_t*)0x20007316 = 0;
  *(uint8_t*)0x20007317 = 0;
  *(uint32_t*)0x20007318 = htobe32(0);
  *(uint32_t*)0x2000731c = htobe32(0);
  *(uint32_t*)0x20007320 = htobe32(0);
  *(uint32_t*)0x20007324 = htobe32(0);
  *(uint32_t*)0x20007328 = htobe32(0);
  *(uint32_t*)0x2000732c = htobe32(0);
  *(uint32_t*)0x20007330 = htobe32(0);
  *(uint32_t*)0x20007334 = htobe32(0);
  memcpy((void*)0x20007338,
         "\x74\x75\x6e\x84\x30\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00",
         16);
  *(uint8_t*)0x20007348 = 0x73;
  *(uint8_t*)0x20007349 = 0x79;
  *(uint8_t*)0x2000734a = 0x7a;
  *(uint8_t*)0x2000734b = 0;
  *(uint8_t*)0x2000734c = 0;
  *(uint8_t*)0x20007358 = 0;
  *(uint8_t*)0x20007359 = 0;
  *(uint8_t*)0x2000735a = 0;
  *(uint8_t*)0x2000735b = 0;
  *(uint8_t*)0x2000735c = 0;
  *(uint8_t*)0x2000735d = 0;
  *(uint8_t*)0x2000735e = 0;
  *(uint8_t*)0x2000735f = 0;
  *(uint8_t*)0x20007360 = 0;
  *(uint8_t*)0x20007361 = 0;
  *(uint8_t*)0x20007362 = 0;
  *(uint8_t*)0x20007363 = 0;
  *(uint8_t*)0x20007364 = 0;
  *(uint8_t*)0x20007365 = 0;
  *(uint8_t*)0x20007366 = 0;
  *(uint8_t*)0x20007367 = 0;
  *(uint8_t*)0x20007368 = 0;
  *(uint8_t*)0x20007369 = 0;
  *(uint8_t*)0x2000736a = 0;
  *(uint8_t*)0x2000736b = 0;
  *(uint8_t*)0x2000736c = 0;
  *(uint8_t*)0x2000736d = 0;
  *(uint8_t*)0x2000736e = 0;
  *(uint8_t*)0x2000736f = 0;
  *(uint8_t*)0x20007370 = 0;
  *(uint8_t*)0x20007371 = 0;
  *(uint8_t*)0x20007372 = 0;
  *(uint8_t*)0x20007373 = 0;
  *(uint8_t*)0x20007374 = 0;
  *(uint8_t*)0x20007375 = 0;
  *(uint8_t*)0x20007376 = 0;
  *(uint8_t*)0x20007377 = 0;
  *(uint16_t*)0x20007378 = 0;
  *(uint8_t*)0x2000737a = 0;
  *(uint8_t*)0x2000737b = 0;
  *(uint8_t*)0x2000737c = 0;
  *(uint32_t*)0x20007380 = 0;
  *(uint16_t*)0x20007384 = 0xa8;
  *(uint16_t*)0x20007386 = 0x110;
  *(uint32_t*)0x20007388 = 0;
  *(uint64_t*)0x2000738c = 0;
  *(uint64_t*)0x20007394 = 0;
  *(uint16_t*)0x200073a0 = 0x68;
  memcpy((void*)0x200073a2, "\x43\x54\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
                            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
                            "\x00\x00\x00\x00\x00",
         29);
  *(uint8_t*)0x200073bf = 1;
  *(uint16_t*)0x200073c0 = 0;
  *(uint16_t*)0x200073c2 = 0;
  *(uint32_t*)0x200073c4 = 0;
  *(uint32_t*)0x200073c8 = 0;
  memcpy((void*)0x200073cc,
         "\x73\x6e\x6d\x70\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00",
         16);
  memcpy((void*)0x200073dc, "\x73\x79\x7a\x31\x00\x00\x00\x00\x00\x00\x00\x00"
                            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
                            "\x00\x00\x00\x00\x00\x00\x00\x00",
         32);
  *(uint64_t*)0x20007400 = 0;
  *(uint64_t*)0x20004000 = 0;
  *(uint64_t*)0x20004008 = 0;
  *(uint64_t*)0x20004010 = 0;
  *(uint64_t*)0x20004018 = 0;
  *(uint64_t*)0x20004020 = 0;
  *(uint64_t*)0x20004028 = 0;
  *(uint64_t*)0x20004030 = 0;
  *(uint64_t*)0x20004038 = 0;
  syscall(__NR_setsockopt, r[0], 0x29, 0x40, 0x20007000, 0x408);
  r[1] = syscall(__NR_socket, 0xa, 5, 0x84);
  *(uint32_t*)0x20d6cf78 = 1;
  *(uint16_t*)0x20d6cf80 = 0xa;
  *(uint16_t*)0x20d6cf82 = htobe16(0x4e20);
  *(uint32_t*)0x20d6cf84 = 0;
  *(uint8_t*)0x20d6cf88 = -1;
  *(uint8_t*)0x20d6cf89 = 1;
  *(uint8_t*)0x20d6cf8a = 0;
  *(uint8_t*)0x20d6cf8b = 0;
  *(uint8_t*)0x20d6cf8c = 0;
  *(uint8_t*)0x20d6cf8d = 0;
  *(uint8_t*)0x20d6cf8e = 0;
  *(uint8_t*)0x20d6cf8f = 0;
  *(uint8_t*)0x20d6cf90 = 0;
  *(uint8_t*)0x20d6cf91 = 0;
  *(uint8_t*)0x20d6cf92 = 0;
  *(uint8_t*)0x20d6cf93 = 0;
  *(uint8_t*)0x20d6cf94 = 0;
  *(uint8_t*)0x20d6cf95 = 0;
  *(uint8_t*)0x20d6cf96 = 0;
  *(uint8_t*)0x20d6cf97 = 1;
  *(uint32_t*)0x20d6cf98 = 0;
  *(uint64_t*)0x20d6cfa0 = 0;
  *(uint64_t*)0x20d6cfa8 = 0;
  *(uint64_t*)0x20d6cfb0 = 0;
  *(uint64_t*)0x20d6cfb8 = 0;
  *(uint64_t*)0x20d6cfc0 = 0;
  *(uint64_t*)0x20d6cfc8 = 0;
  *(uint64_t*)0x20d6cfd0 = 0;
  *(uint64_t*)0x20d6cfd8 = 0;
  *(uint64_t*)0x20d6cfe0 = 0;
  *(uint64_t*)0x20d6cfe8 = 0;
  *(uint64_t*)0x20d6cff0 = 0;
  *(uint64_t*)0x20d6cff8 = 0;
  syscall(__NR_setsockopt, r[1], 0x29, 0x2a, 0x20d6cf78, 0x88);
  *(uint8_t*)0x2000d000 = -1;
  *(uint8_t*)0x2000d001 = -1;
  *(uint8_t*)0x2000d002 = -1;
  *(uint8_t*)0x2000d003 = -1;
  *(uint8_t*)0x2000d004 = -1;
  *(uint8_t*)0x2000d005 = -1;
  *(uint8_t*)0x2000d006 = 0xaa;
  *(uint8_t*)0x2000d007 = 0xaa;
  *(uint8_t*)0x2000d008 = 0xaa;
  *(uint8_t*)0x2000d009 = 0xaa;
  *(uint8_t*)0x2000d00a = 0;
  *(uint8_t*)0x2000d00b = 0;
  *(uint16_t*)0x2000d00c = htobe16(0x800);
  STORE_BY_BITMASK(uint8_t, 0x2000d00e, 5, 0, 4);
  STORE_BY_BITMASK(uint8_t, 0x2000d00e, 4, 4, 4);
  STORE_BY_BITMASK(uint8_t, 0x2000d00f, 0, 0, 2);
  STORE_BY_BITMASK(uint8_t, 0x2000d00f, 0, 2, 6);
  *(uint16_t*)0x2000d010 = htobe16(0x70);
  *(uint16_t*)0x2000d012 = 0;
  *(uint16_t*)0x2000d014 = htobe16(0);
  *(uint8_t*)0x2000d016 = 0;
  *(uint8_t*)0x2000d017 = 1;
  *(uint16_t*)0x2000d018 = 0;
  *(uint8_t*)0x2000d01a = 0xac;
  *(uint8_t*)0x2000d01b = 0x14;
  *(uint8_t*)0x2000d01c = 0;
  *(uint8_t*)0x2000d01d = 0xaa;
  *(uint8_t*)0x2000d01e = 0xac;
  *(uint8_t*)0x2000d01f = 0x14;
  *(uint8_t*)0x2000d020 = 0;
  *(uint8_t*)0x2000d021 = 0xaa;
  *(uint8_t*)0x2000d022 = 3;
  *(uint8_t*)0x2000d023 = 0;
  *(uint16_t*)0x2000d024 = 0;
  *(uint8_t*)0x2000d026 = 0;
  *(uint8_t*)0x2000d027 = 0;
  *(uint16_t*)0x2000d028 = htobe16(0);
  STORE_BY_BITMASK(uint8_t, 0x2000d02a, 0x15, 0, 4);
  STORE_BY_BITMASK(uint8_t, 0x2000d02a, 4, 4, 4);
  STORE_BY_BITMASK(uint8_t, 0x2000d02b, 0, 0, 2);
  STORE_BY_BITMASK(uint8_t, 0x2000d02b, 0, 2, 6);
  *(uint16_t*)0x2000d02c = htobe16(0);
  *(uint16_t*)0x2000d02e = 0;
  *(uint16_t*)0x2000d030 = htobe16(0);
  *(uint8_t*)0x2000d032 = 0;
  *(uint8_t*)0x2000d033 = 0x6c;
  *(uint16_t*)0x2000d034 = htobe16(0);
  *(uint32_t*)0x2000d036 = htobe32(0);
  *(uint8_t*)0x2000d03a = 0xac;
  *(uint8_t*)0x2000d03b = 0x14;
  *(uint8_t*)0x2000d03c = 0;
  *(uint8_t*)0x2000d03d = 0;
  *(uint8_t*)0x2000d03e = 0x44;
  *(uint8_t*)0x2000d03f = 0x40;
  *(uint8_t*)0x2000d040 = 0;
  STORE_BY_BITMASK(uint8_t, 0x2000d041, 0, 0, 4);
  STORE_BY_BITMASK(uint8_t, 0x2000d041, 0, 4, 4);
  *(uint32_t*)0x2000d042 = htobe32(0);
  *(uint32_t*)0x2000d046 = htobe32(-1);
  *(uint32_t*)0x2000d04a = htobe32(0);
  *(uint32_t*)0x2000d04e = htobe32(0);
  *(uint32_t*)0x2000d052 = htobe32(0);
  *(uint32_t*)0x2000d056 = htobe32(0xe0000001);
  *(uint32_t*)0x2000d05a = htobe32(0);
  *(uint32_t*)0x2000d05e = htobe32(0xe0000001);
  *(uint32_t*)0x2000d062 = htobe32(0);
  *(uint32_t*)0x2000d066 = htobe32(0);
  *(uint8_t*)0x2000d06a = 0xac;
  *(uint8_t*)0x2000d06b = 0x14;
  *(uint8_t*)0x2000d06c = 0;
  *(uint8_t*)0x2000d06d = 0xaa;
  *(uint32_t*)0x2000d06e = htobe32(0);
  *(uint32_t*)0x2000d072 = htobe32(0);
  *(uint32_t*)0x2000d076 = htobe32(0x7f000001);
  *(uint32_t*)0x2000d07a = htobe32(0);
  struct csum_inet csum_1;
  csum_inet_init(&csum_1);
  csum_inet_update(&csum_1, (const uint8_t*)0x2000d022, 92);
  *(uint16_t*)0x2000d024 = csum_inet_digest(&csum_1);
  struct csum_inet csum_2;
  csum_inet_init(&csum_2);
  csum_inet_update(&csum_2, (const uint8_t*)0x2000d00e, 20);
  *(uint16_t*)0x2000d018 = csum_inet_digest(&csum_2);
  syz_emit_ethernet(0x7e, 0x2000d000, 0x20000000);
  r[2] = syscall(__NR_socket, 2, 3, 9);
  memcpy((void*)0x2000b000, "\x66\x69\x6c\x74\x65\x72\x00\x00\x00\x00\x00\x00"
                            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
                            "\x00\x00\x00\x00\x00\x00\x00\x00",
         32);
  *(uint32_t*)0x2000b020 = 0xe;
  *(uint32_t*)0x2000b024 = 4;
  *(uint32_t*)0x2000b028 = 0x298;
  *(uint32_t*)0x2000b02c = -1;
  *(uint32_t*)0x2000b030 = 0;
  *(uint32_t*)0x2000b034 = 0;
  *(uint32_t*)0x2000b038 = 0;
  *(uint32_t*)0x2000b03c = -1;
  *(uint32_t*)0x2000b040 = -1;
  *(uint32_t*)0x2000b044 = 0;
  *(uint32_t*)0x2000b048 = 0;
  *(uint32_t*)0x2000b04c = 0;
  *(uint32_t*)0x2000b050 = -1;
  *(uint32_t*)0x2000b054 = 4;
  *(uint64_t*)0x2000b058 = 0x20012fc0;
  *(uint8_t*)0x2000b060 = 0;
  *(uint8_t*)0x2000b061 = 0;
  *(uint8_t*)0x2000b062 = 0;
  *(uint8_t*)0x2000b063 = 0;
  *(uint8_t*)0x2000b064 = 0;
  *(uint8_t*)0x2000b065 = 0;
  *(uint8_t*)0x2000b066 = 0;
  *(uint8_t*)0x2000b067 = 0;
  *(uint8_t*)0x2000b068 = 0;
  *(uint8_t*)0x2000b069 = 0;
  *(uint8_t*)0x2000b06a = 0;
  *(uint8_t*)0x2000b06b = 0;
  *(uint8_t*)0x2000b06c = 0;
  *(uint8_t*)0x2000b06d = 0;
  *(uint8_t*)0x2000b06e = 0;
  *(uint8_t*)0x2000b06f = 0;
  *(uint8_t*)0x2000b070 = 0;
  *(uint8_t*)0x2000b071 = 0;
  *(uint8_t*)0x2000b072 = 0;
  *(uint8_t*)0x2000b073 = 0;
  *(uint8_t*)0x2000b074 = 0;
  *(uint8_t*)0x2000b075 = 0;
  *(uint8_t*)0x2000b076 = 0;
  *(uint8_t*)0x2000b077 = 0;
  *(uint8_t*)0x2000b078 = 0;
  *(uint8_t*)0x2000b079 = 0;
  *(uint8_t*)0x2000b07a = 0;
  *(uint8_t*)0x2000b07b = 0;
  *(uint8_t*)0x2000b07c = 0;
  *(uint8_t*)0x2000b07d = 0;
  *(uint8_t*)0x2000b07e = 0;
  *(uint8_t*)0x2000b07f = 0;
  *(uint8_t*)0x2000b080 = 0;
  *(uint8_t*)0x2000b081 = 0;
  *(uint8_t*)0x2000b082 = 0;
  *(uint8_t*)0x2000b083 = 0;
  *(uint8_t*)0x2000b084 = 0;
  *(uint8_t*)0x2000b085 = 0;
  *(uint8_t*)0x2000b086 = 0;
  *(uint8_t*)0x2000b087 = 0;
  *(uint8_t*)0x2000b088 = 0;
  *(uint8_t*)0x2000b089 = 0;
  *(uint8_t*)0x2000b08a = 0;
  *(uint8_t*)0x2000b08b = 0;
  *(uint8_t*)0x2000b08c = 0;
  *(uint8_t*)0x2000b08d = 0;
  *(uint8_t*)0x2000b08e = 0;
  *(uint8_t*)0x2000b08f = 0;
  *(uint8_t*)0x2000b090 = 0;
  *(uint8_t*)0x2000b091 = 0;
  *(uint8_t*)0x2000b092 = 0;
  *(uint8_t*)0x2000b093 = 0;
  *(uint8_t*)0x2000b094 = 0;
  *(uint8_t*)0x2000b095 = 0;
  *(uint8_t*)0x2000b096 = 0;
  *(uint8_t*)0x2000b097 = 0;
  *(uint8_t*)0x2000b098 = 0;
  *(uint8_t*)0x2000b099 = 0;
  *(uint8_t*)0x2000b09a = 0;
  *(uint8_t*)0x2000b09b = 0;
  *(uint8_t*)0x2000b09c = 0;
  *(uint8_t*)0x2000b09d = 0;
  *(uint8_t*)0x2000b09e = 0;
  *(uint8_t*)0x2000b09f = 0;
  *(uint8_t*)0x2000b0a0 = 0;
  *(uint8_t*)0x2000b0a1 = 0;
  *(uint8_t*)0x2000b0a2 = 0;
  *(uint8_t*)0x2000b0a3 = 0;
  *(uint8_t*)0x2000b0a4 = 0;
  *(uint8_t*)0x2000b0a5 = 0;
  *(uint8_t*)0x2000b0a6 = 0;
  *(uint8_t*)0x2000b0a7 = 0;
  *(uint8_t*)0x2000b0a8 = 0;
  *(uint8_t*)0x2000b0a9 = 0;
  *(uint8_t*)0x2000b0aa = 0;
  *(uint8_t*)0x2000b0ab = 0;
  *(uint8_t*)0x2000b0ac = 0;
  *(uint8_t*)0x2000b0ad = 0;
  *(uint8_t*)0x2000b0ae = 0;
  *(uint8_t*)0x2000b0af = 0;
  *(uint8_t*)0x2000b0b0 = 0;
  *(uint8_t*)0x2000b0b1 = 0;
  *(uint8_t*)0x2000b0b2 = 0;
  *(uint8_t*)0x2000b0b3 = 0;
  *(uint32_t*)0x2000b0b4 = 0;
  *(uint16_t*)0x2000b0b8 = 0x70;
  *(uint16_t*)0x2000b0ba = 0x98;
  *(uint32_t*)0x2000b0bc = 0;
  *(uint64_t*)0x2000b0c0 = 0;
  *(uint64_t*)0x2000b0c8 = 0;
  *(uint16_t*)0x2000b0d0 = 0x28;
  memcpy((void*)0x2000b0d2, "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
                            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
                            "\x00\x00\x00\x00\x00",
         29);
  *(uint8_t*)0x2000b0ef = 0;
  *(uint32_t*)0x2000b0f0 = 0xfffffffe;
  *(uint32_t*)0x2000b0f8 = htobe32(0);
  *(uint8_t*)0x2000b0fc = 0xac;
  *(uint8_t*)0x2000b0fd = 0x14;
  *(uint8_t*)0x2000b0fe = 0;
  *(uint8_t*)0x2000b0ff = 0;
  *(uint32_t*)0x2000b100 = htobe32(0);
  *(uint32_t*)0x2000b104 = htobe32(0);
  *(uint8_t*)0x2000b108 = 0x73;
  *(uint8_t*)0x2000b109 = 0x79;
  *(uint8_t*)0x2000b10a = 0x7a;
  *(uint8_t*)0x2000b10b = 0;
  *(uint8_t*)0x2000b10c = 0;
  *(uint8_t*)0x2000b118 = 0x73;
  *(uint8_t*)0x2000b119 = 0x79;
  *(uint8_t*)0x2000b11a = 0x7a;
  *(uint8_t*)0x2000b11b = 0;
  *(uint8_t*)0x2000b11c = 0;
  *(uint8_t*)0x2000b128 = 0;
  *(uint8_t*)0x2000b129 = 0;
  *(uint8_t*)0x2000b12a = 0;
  *(uint8_t*)0x2000b12b = 0;
  *(uint8_t*)0x2000b12c = 0;
  *(uint8_t*)0x2000b12d = 0;
  *(uint8_t*)0x2000b12e = 0;
  *(uint8_t*)0x2000b12f = 0;
  *(uint8_t*)0x2000b130 = 0;
  *(uint8_t*)0x2000b131 = 0;
  *(uint8_t*)0x2000b132 = 0;
  *(uint8_t*)0x2000b133 = 0;
  *(uint8_t*)0x2000b134 = 0;
  *(uint8_t*)0x2000b135 = 0;
  *(uint8_t*)0x2000b136 = 0;
  *(uint8_t*)0x2000b137 = 0;
  *(uint8_t*)0x2000b138 = 0;
  *(uint8_t*)0x2000b139 = 0;
  *(uint8_t*)0x2000b13a = 0;
  *(uint8_t*)0x2000b13b = 0;
  *(uint8_t*)0x2000b13c = 0;
  *(uint8_t*)0x2000b13d = 0;
  *(uint8_t*)0x2000b13e = 0;
  *(uint8_t*)0x2000b13f = 0;
  *(uint8_t*)0x2000b140 = 0;
  *(uint8_t*)0x2000b141 = 0;
  *(uint8_t*)0x2000b142 = 0;
  *(uint8_t*)0x2000b143 = 0;
  *(uint8_t*)0x2000b144 = 0;
  *(uint8_t*)0x2000b145 = 0;
  *(uint8_t*)0x2000b146 = 0;
  *(uint8_t*)0x2000b147 = 0;
  *(uint16_t*)0x2000b148 = 0;
  *(uint8_t*)0x2000b14a = 0;
  *(uint8_t*)0x2000b14b = 0;
  *(uint32_t*)0x2000b14c = 0;
  *(uint16_t*)0x2000b150 = 0x70;
  *(uint16_t*)0x2000b152 = 0x98;
  *(uint32_t*)0x2000b154 = 0;
  *(uint64_t*)0x2000b158 = 0;
  *(uint64_t*)0x2000b160 = 0;
  *(uint16_t*)0x2000b168 = 0x28;
  memcpy((void*)0x2000b16a, "\x43\x4c\x41\x53\x53\x49\x46\x59\x00\x00\x00\x00"
                            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
                            "\x00\x00\x00\x00\x00",
         29);
  *(uint8_t*)0x2000b187 = 0;
  *(uint32_t*)0x2000b188 = 0;
  *(uint32_t*)0x2000b190 = htobe32(0);
  *(uint32_t*)0x2000b194 = htobe32(0xe0000002);
  *(uint32_t*)0x2000b198 = htobe32(0);
  *(uint32_t*)0x2000b19c = htobe32(0);
  memcpy((void*)0x2000b1a0,
         "\x74\x75\x6e\x6c\x30\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00",
         16);
  memcpy((void*)0x2000b1b0,
         "\x7b\x54\x5c\xd8\xd8\x57\xc5\xe1\xb1\x57\xa3\x10\x3b\xde\x15\xee",
         16);
  *(uint8_t*)0x2000b1c0 = 0;
  *(uint8_t*)0x2000b1c1 = 0;
  *(uint8_t*)0x2000b1c2 = 0;
  *(uint8_t*)0x2000b1c3 = 0;
  *(uint8_t*)0x2000b1c4 = 0;
  *(uint8_t*)0x2000b1c5 = 0;
  *(uint8_t*)0x2000b1c6 = 0;
  *(uint8_t*)0x2000b1c7 = 0;
  *(uint8_t*)0x2000b1c8 = 0;
  *(uint8_t*)0x2000b1c9 = 0;
  *(uint8_t*)0x2000b1ca = 0;
  *(uint8_t*)0x2000b1cb = 0;
  *(uint8_t*)0x2000b1cc = 0;
  *(uint8_t*)0x2000b1cd = 0;
  *(uint8_t*)0x2000b1ce = 0;
  *(uint8_t*)0x2000b1cf = 0;
  *(uint8_t*)0x2000b1d0 = 0;
  *(uint8_t*)0x2000b1d1 = 0;
  *(uint8_t*)0x2000b1d2 = 0;
  *(uint8_t*)0x2000b1d3 = 0;
  *(uint8_t*)0x2000b1d4 = 0;
  *(uint8_t*)0x2000b1d5 = 0;
  *(uint8_t*)0x2000b1d6 = 0;
  *(uint8_t*)0x2000b1d7 = 0;
  *(uint8_t*)0x2000b1d8 = 0;
  *(uint8_t*)0x2000b1d9 = 0;
  *(uint8_t*)0x2000b1da = 0;
  *(uint8_t*)0x2000b1db = 0;
  *(uint8_t*)0x2000b1dc = 0;
  *(uint8_t*)0x2000b1dd = 0;
  *(uint8_t*)0x2000b1de = 0;
  *(uint8_t*)0x2000b1df = 0;
  *(uint16_t*)0x2000b1e0 = 0;
  *(uint8_t*)0x2000b1e2 = 0;
  *(uint8_t*)0x2000b1e3 = 0;
  *(uint32_t*)0x2000b1e4 = 0;
  *(uint16_t*)0x2000b1e8 = 0x70;
  *(uint16_t*)0x2000b1ea = 0x98;
  *(uint32_t*)0x2000b1ec = 0;
  *(uint64_t*)0x2000b1f0 = 0;
  *(uint64_t*)0x2000b1f8 = 0;
  *(uint16_t*)0x2000b200 = 0x28;
  memcpy((void*)0x2000b202, "\x52\x45\x4a\x45\x43\x54\x00\x00\x00\x00\x00\x00"
                            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
                            "\x00\x00\x00\x00\x00",
         29);
  *(uint8_t*)0x2000b21f = 0;
  *(uint32_t*)0x2000b220 = 0;
  *(uint32_t*)0x2000b228 = htobe32(0);
  *(uint32_t*)0x2000b22c = htobe32(0xe0000002);
  *(uint32_t*)0x2000b230 = htobe32(0);
  *(uint32_t*)0x2000b234 = htobe32(-1);
  *(uint8_t*)0x2000b238 = 0x73;
  *(uint8_t*)0x2000b239 = 0x79;
  *(uint8_t*)0x2000b23a = 0x7a;
  *(uint8_t*)0x2000b23b = 0x30;
  *(uint8_t*)0x2000b23c = 0;
  *(uint8_t*)0x2000b248 = 0x73;
  *(uint8_t*)0x2000b249 = 0x79;
  *(uint8_t*)0x2000b24a = 0x7a;
  *(uint8_t*)0x2000b24b = 0;
  *(uint8_t*)0x2000b24c = 0;
  *(uint8_t*)0x2000b258 = 0;
  *(uint8_t*)0x2000b259 = 0;
  *(uint8_t*)0x2000b25a = 0;
  *(uint8_t*)0x2000b25b = 0;
  *(uint8_t*)0x2000b25c = 0;
  *(uint8_t*)0x2000b25d = 0;
  *(uint8_t*)0x2000b25e = 0;
  *(uint8_t*)0x2000b25f = 0;
  *(uint8_t*)0x2000b260 = 0;
  *(uint8_t*)0x2000b261 = 0;
  *(uint8_t*)0x2000b262 = 0;
  *(uint8_t*)0x2000b263 = 0;
  *(uint8_t*)0x2000b264 = 0;
  *(uint8_t*)0x2000b265 = 0;
  *(uint8_t*)0x2000b266 = 0;
  *(uint8_t*)0x2000b267 = 0;
  *(uint8_t*)0x2000b268 = 0;
  *(uint8_t*)0x2000b269 = 0;
  *(uint8_t*)0x2000b26a = 0;
  *(uint8_t*)0x2000b26b = 0;
  *(uint8_t*)0x2000b26c = 0;
  *(uint8_t*)0x2000b26d = 0;
  *(uint8_t*)0x2000b26e = 0;
  *(uint8_t*)0x2000b26f = 0;
  *(uint8_t*)0x2000b270 = 0;
  *(uint8_t*)0x2000b271 = 0;
  *(uint8_t*)0x2000b272 = 0;
  *(uint8_t*)0x2000b273 = 0;
  *(uint8_t*)0x2000b274 = 0;
  *(uint8_t*)0x2000b275 = 0;
  *(uint8_t*)0x2000b276 = 0;
  *(uint8_t*)0x2000b277 = 0;
  *(uint16_t*)0x2000b278 = 0;
  *(uint8_t*)0x2000b27a = 0;
  *(uint8_t*)0x2000b27b = 0;
  *(uint32_t*)0x2000b27c = 0;
  *(uint16_t*)0x2000b280 = 0x70;
  *(uint16_t*)0x2000b282 = 0xd0;
  *(uint32_t*)0x2000b284 = 0;
  *(uint64_t*)0x2000b288 = 0;
  *(uint64_t*)0x2000b290 = 0;
  *(uint16_t*)0x2000b298 = 0x60;
  memcpy((void*)0x2000b29a, "\x43\x4c\x55\x53\x54\x45\x52\x49\x50\x00\x00\x00"
                            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
                            "\x00\x00\x00\x00\x00",
         29);
  *(uint8_t*)0x2000b2b7 = 0;
  *(uint32_t*)0x2000b2b8 = 1;
  *(uint8_t*)0x2000b2bc = 1;
  *(uint8_t*)0x2000b2bd = 0x80;
  *(uint8_t*)0x2000b2be = 0xc2;
  *(uint8_t*)0x2000b2bf = 0;
  *(uint8_t*)0x2000b2c0 = 0;
  *(uint8_t*)0x2000b2c1 = 0;
  *(uint16_t*)0x2000b2c2 = 0;
  *(uint16_t*)0x2000b2c4 = 0;
  *(uint16_t*)0x2000b2c6 = 0;
  *(uint16_t*)0x2000b2c8 = 0;
  *(uint16_t*)0x2000b2ca = 0;
  *(uint16_t*)0x2000b2cc = 0;
  *(uint16_t*)0x2000b2ce = 0;
  *(uint16_t*)0x2000b2d0 = 0;
  *(uint16_t*)0x2000b2d2 = 0;
  *(uint16_t*)0x2000b2d4 = 0;
  *(uint16_t*)0x2000b2d6 = 0;
  *(uint16_t*)0x2000b2d8 = 0;
  *(uint16_t*)0x2000b2da = 0;
  *(uint16_t*)0x2000b2dc = 0;
  *(uint16_t*)0x2000b2de = 0;
  *(uint16_t*)0x2000b2e0 = 0;
  *(uint16_t*)0x2000b2e2 = 0;
  *(uint16_t*)0x2000b2e4 = 0;
  *(uint32_t*)0x2000b2e8 = 0;
  *(uint32_t*)0x2000b2ec = 0;
  *(uint64_t*)0x2000b2f0 = 0;
  *(uint64_t*)0x20012fc0 = 0;
  *(uint64_t*)0x20012fc8 = 0;
  *(uint64_t*)0x20012fd0 = 0;
  *(uint64_t*)0x20012fd8 = 0;
  *(uint64_t*)0x20012fe0 = 0;
  *(uint64_t*)0x20012fe8 = 0;
  *(uint64_t*)0x20012ff0 = 0;
  *(uint64_t*)0x20012ff8 = 0;
  syscall(__NR_setsockopt, r[2], 0, 0x40, 0x2000b000, 0x2f8);
}

int main()
{
  for (;;) {
    setup_tun(0, true);
    loop();
  }
}
