// https://syzkaller.appspot.com/bug?id=3decf6091df2b1c514270c36e111076d7db1b5ce
// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
  syscall(__NR_mmap, /*addr=*/0x1ffffffff000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x200000000000ul, /*len=*/0x1000000ul,
          /*prot=PROT_WRITE|PROT_READ|PROT_EXEC*/ 7ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x200001000000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  const char* reason;
  (void)reason;
  intptr_t res = 0;
  if (write(1, "executing program\n", sizeof("executing program\n") - 1)) {
  }
  syscall(__NR_bind, /*fd=*/(intptr_t)-1, /*addr=*/0ul, /*addrlen=*/0ul);
  res = syscall(__NR_socket, /*domain=*/0xaul, /*type=*/2ul, /*proto=*/0x88);
  if (res != -1)
    r[0] = res;
  *(uint8_t*)0x200000000340 = 0xfc;
  *(uint8_t*)0x200000000341 = 0;
  memset((void*)0x200000000342, 0, 13);
  *(uint8_t*)0x20000000034f = 1;
  *(uint8_t*)0x200000000350 = -1;
  *(uint8_t*)0x200000000351 = 2;
  memset((void*)0x200000000352, 0, 13);
  *(uint8_t*)0x20000000035f = 1;
  memset((void*)0x200000000360, 0, 16);
  *(uint32_t*)0x200000000370 = 0xc16;
  *(uint16_t*)0x200000000374 = 0x1c10;
  *(uint16_t*)0x200000000376 = 0xfff0;
  *(uint32_t*)0x200000000378 = 0xc00;
  *(uint64_t*)0x200000000380 = 0x7be;
  *(uint32_t*)0x200000000388 = 0x202;
  *(uint32_t*)0x20000000038c = 0;
  syscall(__NR_ioctl, /*fd=*/r[0], /*cmd=*/0x890b, /*arg=*/0x200000000340ul);
  return 0;
}
