// https://syzkaller.appspot.com/bug?id=d369eafab7836fe0dd2e027d2689da06cad8e1a3
// autogenerated by syzkaller (http://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <errno.h>
#include <pthread.h>
#include <signal.h>
#include <stdarg.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/prctl.h>
#include <sys/syscall.h>
#include <sys/time.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

const int kFailStatus = 67;
const int kRetryStatus = 69;

__attribute__((noreturn)) static void doexit(int status)
{
  volatile unsigned i;
  syscall(__NR_exit_group, status);
  for (i = 0;; i++) {
  }
}

__attribute__((noreturn)) static void fail(const char* msg, ...)
{
  int e = errno;
  fflush(stdout);
  va_list args;
  va_start(args, msg);
  vfprintf(stderr, msg, args);
  va_end(args);
  fprintf(stderr, " (errno %d)\n", e);
  doexit((e == ENOMEM || e == EAGAIN) ? kRetryStatus : kFailStatus);
}

__attribute__((noreturn)) static void exitf(const char* msg, ...)
{
  int e = errno;
  fflush(stdout);
  va_list args;
  va_start(args, msg);
  vfprintf(stderr, msg, args);
  va_end(args);
  fprintf(stderr, " (errno %d)\n", e);
  doexit(kRetryStatus);
}

static uint64_t current_time_ms()
{
  struct timespec ts;

  if (clock_gettime(CLOCK_MONOTONIC, &ts))
    fail("clock_gettime failed");
  return (uint64_t)ts.tv_sec * 1000 + (uint64_t)ts.tv_nsec / 1000000;
}

static void test();

void loop()
{
  int iter;
  for (iter = 0;; iter++) {
    int pid = fork();
    if (pid < 0)
      fail("clone failed");
    if (pid == 0) {
      prctl(PR_SET_PDEATHSIG, SIGKILL, 0, 0, 0);
      setpgrp();
      test();
      doexit(0);
    }
    int status = 0;
    uint64_t start = current_time_ms();
    for (;;) {
      int res = waitpid(-1, &status, __WALL | WNOHANG);
      if (res == pid)
        break;
      usleep(1000);
      if (current_time_ms() - start > 5 * 1000) {
        kill(-pid, SIGKILL);
        kill(pid, SIGKILL);
        while (waitpid(-1, &status, __WALL) != pid) {
        }
        break;
      }
    }
  }
}

long r[70];
void* thr(void* arg)
{
  switch ((long)arg) {
  case 0:
    r[0] = syscall(__NR_mmap, 0x20000000ul, 0xafb000ul, 0x3ul, 0x32ul,
                   0xfffffffffffffffful, 0x0ul);
    break;
  case 1:
    memcpy((void*)0x206a8000, "\x2f\x64\x65\x76\x2f\x6b\x76\x6d\x00",
           9);
    r[2] = syscall(__NR_openat, 0xffffffffffffff9cul, 0x206a8000ul,
                   0x0ul, 0x0ul);
    break;
  case 2:
    r[3] = syscall(__NR_ioctl, r[2], 0xae01ul, 0x0ul);
    break;
  case 3:
    *(uint32_t*)0x20af8000 = (uint32_t)0x0;
    *(uint32_t*)0x20af8004 = (uint32_t)0x0;
    *(uint32_t*)0x20af8008 = (uint32_t)0x2;
    memcpy((void*)0x20af800c,
           "\x71\x75\x65\x75\x65\x30\x00\x00\x00\x00\x00\x00\x00\x00"
           "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
           "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
           "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
           "\x00\x00\x00\x00\x00\x00\x00\x00",
           64);
    *(uint32_t*)0x20af804c = (uint32_t)0x5;
    *(uint8_t*)0x20af8050 = (uint8_t)0x0;
    *(uint8_t*)0x20af8051 = (uint8_t)0x0;
    *(uint8_t*)0x20af8052 = (uint8_t)0x0;
    *(uint8_t*)0x20af8053 = (uint8_t)0x0;
    *(uint8_t*)0x20af8054 = (uint8_t)0x0;
    *(uint8_t*)0x20af8055 = (uint8_t)0x0;
    *(uint8_t*)0x20af8056 = (uint8_t)0x0;
    *(uint8_t*)0x20af8057 = (uint8_t)0x0;
    *(uint8_t*)0x20af8058 = (uint8_t)0x0;
    *(uint8_t*)0x20af8059 = (uint8_t)0x0;
    *(uint8_t*)0x20af805a = (uint8_t)0x0;
    *(uint8_t*)0x20af805b = (uint8_t)0x0;
    *(uint8_t*)0x20af805c = (uint8_t)0x0;
    *(uint8_t*)0x20af805d = (uint8_t)0x0;
    *(uint8_t*)0x20af805e = (uint8_t)0x0;
    *(uint8_t*)0x20af805f = (uint8_t)0x0;
    *(uint8_t*)0x20af8060 = (uint8_t)0x0;
    *(uint8_t*)0x20af8061 = (uint8_t)0x0;
    *(uint8_t*)0x20af8062 = (uint8_t)0x0;
    *(uint8_t*)0x20af8063 = (uint8_t)0x0;
    *(uint8_t*)0x20af8064 = (uint8_t)0x0;
    *(uint8_t*)0x20af8065 = (uint8_t)0x0;
    *(uint8_t*)0x20af8066 = (uint8_t)0x0;
    *(uint8_t*)0x20af8067 = (uint8_t)0x0;
    *(uint8_t*)0x20af8068 = (uint8_t)0x0;
    *(uint8_t*)0x20af8069 = (uint8_t)0x0;
    *(uint8_t*)0x20af806a = (uint8_t)0x0;
    *(uint8_t*)0x20af806b = (uint8_t)0x0;
    *(uint8_t*)0x20af806c = (uint8_t)0x0;
    *(uint8_t*)0x20af806d = (uint8_t)0x0;
    *(uint8_t*)0x20af806e = (uint8_t)0x0;
    *(uint8_t*)0x20af806f = (uint8_t)0x0;
    *(uint8_t*)0x20af8070 = (uint8_t)0x0;
    *(uint8_t*)0x20af8071 = (uint8_t)0x0;
    *(uint8_t*)0x20af8072 = (uint8_t)0x0;
    *(uint8_t*)0x20af8073 = (uint8_t)0x0;
    *(uint8_t*)0x20af8074 = (uint8_t)0x0;
    *(uint8_t*)0x20af8075 = (uint8_t)0x0;
    *(uint8_t*)0x20af8076 = (uint8_t)0x0;
    *(uint8_t*)0x20af8077 = (uint8_t)0x0;
    *(uint8_t*)0x20af8078 = (uint8_t)0x0;
    *(uint8_t*)0x20af8079 = (uint8_t)0x0;
    *(uint8_t*)0x20af807a = (uint8_t)0x0;
    *(uint8_t*)0x20af807b = (uint8_t)0x0;
    *(uint8_t*)0x20af807c = (uint8_t)0x0;
    *(uint8_t*)0x20af807d = (uint8_t)0x0;
    *(uint8_t*)0x20af807e = (uint8_t)0x0;
    *(uint8_t*)0x20af807f = (uint8_t)0x0;
    *(uint8_t*)0x20af8080 = (uint8_t)0x0;
    *(uint8_t*)0x20af8081 = (uint8_t)0x0;
    *(uint8_t*)0x20af8082 = (uint8_t)0x0;
    *(uint8_t*)0x20af8083 = (uint8_t)0x0;
    *(uint8_t*)0x20af8084 = (uint8_t)0x0;
    *(uint8_t*)0x20af8085 = (uint8_t)0x0;
    *(uint8_t*)0x20af8086 = (uint8_t)0x0;
    *(uint8_t*)0x20af8087 = (uint8_t)0x0;
    *(uint8_t*)0x20af8088 = (uint8_t)0x0;
    *(uint8_t*)0x20af8089 = (uint8_t)0x0;
    *(uint8_t*)0x20af808a = (uint8_t)0x0;
    *(uint8_t*)0x20af808b = (uint8_t)0x0;
    r[69] = syscall(__NR_ioctl, 0xfffffffffffffffful, 0x408c5333ul,
                    0x20af8000ul);
    break;
  }
  return 0;
}

void test()
{
  long i;
  pthread_t th[8];

  memset(r, -1, sizeof(r));
  srand(getpid());
  for (i = 0; i < 4; i++) {
    pthread_create(&th[i], 0, thr, (void*)i);
    usleep(rand() % 10000);
  }
  for (i = 0; i < 4; i++) {
    pthread_create(&th[4 + i], 0, thr, (void*)i);
    if (rand() % 2)
      usleep(rand() % 10000);
  }
  usleep(rand() % 100000);
}

int main()
{
  int i;
  for (i = 0; i < 8; i++) {
    if (fork() == 0) {
      loop();
      return 0;
    }
  }
  sleep(1000000);
  return 0;
}
