// https://syzkaller.appspot.com/bug?id=f1834e1735946170a8a3a4c85edb978e94bada81
// autogenerated by syzkaller (http://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <errno.h>
#include <signal.h>
#include <stdarg.h>
#include <stdio.h>
#include <sys/prctl.h>
#include <sys/syscall.h>
#include <sys/time.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

__attribute__((noreturn)) static void doexit(int status)
{
  volatile unsigned i;
  syscall(__NR_exit_group, status);
  for (i = 0;; i++) {
  }
}

#include <stdint.h>
#include <string.h>

const int kFailStatus = 67;
const int kRetryStatus = 69;

static void fail(const char* msg, ...)
{
  int e = errno;
  va_list args;
  va_start(args, msg);
  vfprintf(stderr, msg, args);
  va_end(args);
  fprintf(stderr, " (errno %d)\n", e);
  doexit((e == ENOMEM || e == EAGAIN) ? kRetryStatus : kFailStatus);
}

static uint64_t current_time_ms()
{
  struct timespec ts;

  if (clock_gettime(CLOCK_MONOTONIC, &ts))
    fail("clock_gettime failed");
  return (uint64_t)ts.tv_sec * 1000 + (uint64_t)ts.tv_nsec / 1000000;
}

static void test();

void loop()
{
  int iter;
  for (iter = 0;; iter++) {
    int pid = fork();
    if (pid < 0)
      fail("clone failed");
    if (pid == 0) {
      prctl(PR_SET_PDEATHSIG, SIGKILL, 0, 0, 0);
      setpgrp();
      test();
      doexit(0);
    }
    int status = 0;
    uint64_t start = current_time_ms();
    for (;;) {
      int res = waitpid(-1, &status, __WALL | WNOHANG);
      if (res == pid)
        break;
      usleep(1000);
      if (current_time_ms() - start > 5 * 1000) {
        kill(-pid, SIGKILL);
        kill(pid, SIGKILL);
        while (waitpid(-1, &status, __WALL) != pid) {
        }
        break;
      }
    }
  }
}

long r[86];
void test()
{
  memset(r, -1, sizeof(r));
  r[0] = syscall(__NR_mmap, 0x20000000ul, 0xf3c000ul, 0x3ul, 0x32ul,
                 0xfffffffffffffffful, 0x0ul);
  r[1] = syscall(__NR_socket, 0x26ul, 0x5ul, 0x0ul);
  *(uint16_t*)0x20e1e000 = (uint16_t)0x26;
  memcpy((void*)0x20e1e002,
         "\x72\x6e\x67\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00",
         14);
  *(uint32_t*)0x20e1e010 = (uint32_t)0x0;
  *(uint32_t*)0x20e1e014 = (uint32_t)0x0;
  memcpy((void*)0x20e1e018,
         "\x64\x72\x62\x67\x5f\x6e\x6f\x70\x72\x5f\x68\x6d\x61\x63\x5f"
         "\x73\x68\x61\x32\x35\x36\x00\x00\x00\x00\x00\x00\x00\x00\x00"
         "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
         "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
         "\x00\x00\x00\x00",
         64);
  r[7] = syscall(__NR_bind, r[1], 0x20e1e000ul, 0x58ul);
  *(uint16_t*)0x20f3b000 = (uint16_t)0x26;
  memcpy((void*)0x20f3b002,
         "\x61\x65\x61\x64\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00",
         14);
  *(uint32_t*)0x20f3b010 = (uint32_t)0x0;
  *(uint32_t*)0x20f3b014 = (uint32_t)0x0;
  memcpy((void*)0x20f3b018,
         "\x72\x66\x63\x34\x31\x30\x36\x28\x67\x63\x6d\x28\x61\x65\x73"
         "\x29\x29\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
         "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
         "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
         "\x00\x00\x00\x00",
         64);
  r[13] = syscall(__NR_bind, r[1], 0x20f3b000ul, 0x58ul);
  r[14] = syscall(__NR_accept, r[1], 0x0ul, 0x0ul);
  r[15] = syscall(__NR_socket, 0x26ul, 0x5ul, 0x0ul);
  *(uint16_t*)0x20a65000 = (uint16_t)0x26;
  memcpy((void*)0x20a65002,
         "\x61\x65\x61\x64\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00",
         14);
  *(uint32_t*)0x20a65010 = (uint32_t)0x0;
  *(uint32_t*)0x20a65014 = (uint32_t)0x8010010000000000;
  memcpy((void*)0x20a65018,
         "\x67\x63\x6d\x28\x73\x65\x72\x70\x65\x6e\x74\x29\x00\x00\x00"
         "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
         "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
         "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
         "\x00\x00\x00\x00",
         64);
  r[21] = syscall(__NR_bind, r[15], 0x20a65000ul, 0x58ul);
  r[22] = syscall(__NR_setsockopt, r[15], 0x117ul, 0x1ul, 0x20001f3aul,
                  0x0ul);
  r[23] = syscall(__NR_accept, r[15], 0x0ul, 0x0ul);
  *(uint64_t*)0x202fefc8 = (uint64_t)0x0;
  *(uint32_t*)0x202fefd0 = (uint32_t)0x0;
  *(uint64_t*)0x202fefd8 = (uint64_t)0x20985000;
  *(uint64_t*)0x202fefe0 = (uint64_t)0x1;
  *(uint64_t*)0x202fefe8 = (uint64_t)0x20632f70;
  *(uint64_t*)0x202feff0 = (uint64_t)0x78;
  *(uint32_t*)0x202feff8 = (uint32_t)0x1;
  *(uint64_t*)0x20985000 = (uint64_t)0x206fdf9d;
  *(uint64_t*)0x20985008 = (uint64_t)0xe;
  memcpy((void*)0x206fdf9d,
         "\x95\x76\xfb\x56\x78\xf4\xd8\xbb\x1b\x8c\x63\xa2\x29\xd9",
         14);
  *(uint64_t*)0x20632f70 = (uint64_t)0x18;
  *(uint32_t*)0x20632f78 = (uint32_t)0x117;
  *(uint32_t*)0x20632f7c = (uint32_t)0x3;
  *(uint32_t*)0x20632f80 = (uint32_t)0x0;
  *(uint64_t*)0x20632f88 = (uint64_t)0x18;
  *(uint32_t*)0x20632f90 = (uint32_t)0x117;
  *(uint32_t*)0x20632f94 = (uint32_t)0x3;
  *(uint32_t*)0x20632f98 = (uint32_t)0x0;
  *(uint64_t*)0x20632fa0 = (uint64_t)0x18;
  *(uint32_t*)0x20632fa8 = (uint32_t)0x117;
  *(uint32_t*)0x20632fac = (uint32_t)0x3;
  *(uint32_t*)0x20632fb0 = (uint32_t)0x1;
  *(uint64_t*)0x20632fb8 = (uint64_t)0x18;
  *(uint32_t*)0x20632fc0 = (uint32_t)0x117;
  *(uint32_t*)0x20632fc4 = (uint32_t)0x4;
  *(uint32_t*)0x20632fc8 = (uint32_t)0x100000000;
  *(uint64_t*)0x20632fd0 = (uint64_t)0x18;
  *(uint32_t*)0x20632fd8 = (uint32_t)0x117;
  *(uint32_t*)0x20632fdc = (uint32_t)0x4;
  *(uint32_t*)0x20632fe0 = (uint32_t)0x3;
  r[54] = syscall(__NR_sendmsg, r[23], 0x202fefc8ul, 0x1ul);
  r[55] = syscall(__NR_io_setup, 0x3ul, 0x20e4b000ul);
  if (r[55] != -1)
    r[56] = *(uint64_t*)0x20e4b000;
  *(uint64_t*)0x20642ff0 = (uint64_t)0x20617fc0;
  *(uint64_t*)0x20642ff8 = (uint64_t)0x20097fc0;
  *(uint64_t*)0x20617fc0 = (uint64_t)0x0;
  *(uint32_t*)0x20617fc8 = (uint32_t)0x0;
  *(uint32_t*)0x20617fcc = (uint32_t)0x0;
  *(uint16_t*)0x20617fd0 = (uint16_t)0x0;
  *(uint16_t*)0x20617fd2 = (uint16_t)0x1;
  *(uint32_t*)0x20617fd4 = r[23];
  *(uint64_t*)0x20617fd8 = (uint64_t)0x2007d000;
  *(uint64_t*)0x20617fe0 = (uint64_t)0xad;
  *(uint64_t*)0x20617fe8 = (uint64_t)0x0;
  *(uint64_t*)0x20617ff0 = (uint64_t)0x0;
  *(uint32_t*)0x20617ff8 = (uint32_t)0x0;
  *(uint32_t*)0x20617ffc = (uint32_t)0xffffffffffffffff;
  memcpy((void*)0x2007d000,
         "\xb3\xb0\x39\x96\xff\x05\xab\xb1\xe8\xb1\xc2\x4b\x50\x89\x8d"
         "\x8f\x9e\xad\x67\x39\x23\xf5\x7e\xea\x9c\x32\x35\x39\xf6\x10"
         "\x98\xa6\x6e\x70\xe2\x1c\x7f\x41\xb2\x48\x34\x36\x90\xcd\xe4"
         "\x38\x3c\x53\x8b\x17\x9b\x0f\x5d\xcc\xcf\x6b\xfa\xf8\x03\x1c"
         "\xb0\x52\xad\x74\xa5\xa8\x3f\xad\xd0\x99\x55\xb1\x67\x6d\x37"
         "\xe5\xe4\x5d\x50\x69\x7c\xe5\x3a\x58\x8a\xe0\xd5\xe6\xe2\x0d"
         "\xf6\x1f\xeb\xd6\x65\xb5\x32\xe5\x79\x0c\x28\x39\xd3\xb8\x06"
         "\x8a\x5d\xeb\x2c\x40\x8f\xc4\x82\xa0\x57\x1c\xd5\x48\xc8\xa8"
         "\xb9\x04\x89\x61\xcc\xef\x04\x33\xf1\x84\x79\xdd\xd0\x92\x36"
         "\xd4\x95\xea\xad\xd8\x35\xe6\x4b\x72\x8d\x0f\x8e\x60\xde\x4c"
         "\x73\xd9\x0e\x62\x66\x41\x0f\xf6\x82\xff\x4b\x33\x8e\x62\xae"
         "\xd8\x53\xf8\xf9\x0f\x83\x2b\xdc",
         173);
  *(uint64_t*)0x20097fc0 = (uint64_t)0x0;
  *(uint32_t*)0x20097fc8 = (uint32_t)0x0;
  *(uint32_t*)0x20097fcc = (uint32_t)0x0;
  *(uint16_t*)0x20097fd0 = (uint16_t)0x7;
  *(uint16_t*)0x20097fd2 = (uint16_t)0xca9;
  *(uint32_t*)0x20097fd4 = r[15];
  *(uint64_t*)0x20097fd8 = (uint64_t)0x202b9000;
  *(uint64_t*)0x20097fe0 = (uint64_t)0x0;
  *(uint64_t*)0x20097fe8 = (uint64_t)0x10000;
  *(uint64_t*)0x20097ff0 = (uint64_t)0x0;
  *(uint32_t*)0x20097ff8 = (uint32_t)0x1;
  *(uint32_t*)0x20097ffc = (uint32_t)0xffffffffffffffff;
  r[84] = syscall(__NR_io_submit, r[56], 0x2ul, 0x20642ff0ul);
  r[85] = syscall(__NR_accept, r[1], 0x0ul, 0x0ul);
}

int main()
{
  int i;
  for (i = 0; i < 8; i++) {
    if (fork() == 0) {
      loop();
      return 0;
    }
  }
  sleep(1000000);
  return 0;
}
