name: Compile reproducers

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - crepros/
      - .github/workflows/compile.yml
  schedule:
    - cron: '0 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Compile reproducers
      run: |
        sudo apt-get install build-essential -y
        ./compile.sh
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
